using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

#pragma warning disable RS1024 // Symbols should be compared for equality

namespace JasperFx.Events.SourceGenerator;

internal static class EvolverCodeEmitter
{
    // Always emit type references with `global::` so generated code is robust to
    // identifiers in the consumer's namespace that shadow a parent namespace name
    // (see https://github.com/JasperFx/jasperfx/issues/288). Default ToDisplayString()
    // omits the alias, which becomes uncompilable when a type like `EventTests` lives
    // in `namespace EventTests`.
    private static string Fqn(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    public static string EmitPartialProjection(CandidateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()};");
            sb.AppendLine();
        }

        // If the projection is declared inside another type (common in xUnit test
        // files where the projection lives next to test methods), emit a matching
        // chain of `partial class Container { ... }` wrappers so the generated
        // partial merges with the user's source partial. See #292.
        var containingTypes = GetContainingTypes(info.ClassSymbol);
        foreach (var container in containingTypes)
        {
            sb.AppendLine($"partial {ContainerKeyword(container)} {container.Name}{ContainerTypeParams(container)}");
            sb.AppendLine("{");
        }

        var className = info.ClassSymbol.Name;

        // Include type parameters if the class is generic
        var typeParams = "";
        if (info.ClassSymbol.TypeParameters.Length > 0)
        {
            typeParams = "<" + string.Join(", ", info.ClassSymbol.TypeParameters.Select(t => t.Name)) + ">";
        }

        sb.AppendLine($"partial class {className}{typeParams}");
        sb.AppendLine("{");

        // Generate constructor that calls IncludeType<T>() for every event type
        EmitConstructorWithIncludeTypes(sb, info, className);
        sb.AppendLine();

        if (info.HasShouldDelete)
        {
            EmitDetermineActionAsyncOverride(sb, info);
        }
        else if (info.HasAnyAsync)
        {
            EmitEvolveAsyncOverride(sb, info);
        }
        else
        {
            EmitEvolveOverride(sb, info);
        }

        sb.AppendLine("}");

        foreach (var _ in containingTypes)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string ContainerTypeParams(INamedTypeSymbol container)
    {
        if (container.TypeParameters.Length == 0) return string.Empty;
        return "<" + string.Join(", ", container.TypeParameters.Select(t => t.Name)) + ">";
    }

    /// <summary>
    /// Returns the type-declaration keyword that matches the user's source.
    /// Required when a projection class is nested inside a record (a fairly
    /// common pattern, e.g. `record Foo { partial class Projector ... }`)
    /// — emitting `partial class Foo` against a `partial record Foo` fails
    /// the build with CS0102 ("already contains a definition").
    /// </summary>
    private static string ContainerKeyword(INamedTypeSymbol container)
    {
        if (container.IsRecord)
        {
            return container.TypeKind == TypeKind.Struct ? "record struct" : "record";
        }

        return container.TypeKind == TypeKind.Struct ? "struct" : "class";
    }

    private static void EmitConstructorWithIncludeTypes(StringBuilder sb, CandidateInfo info, string className)
    {
        var eventTypes = info.Methods.Select(m => Fqn(m.EventType)).Distinct().ToList();
        if (eventTypes.Count == 0) return;

        // Skip if the class already has an explicit parameterless constructor
        if (info.HasExistingParameterlessConstructor) return;

        sb.AppendLine($"    public {className}()");
        sb.AppendLine("    {");
        foreach (var eventType in eventTypes)
        {
            sb.AppendLine($"        IncludeType<{eventType}>();");
        }
        sb.AppendLine("    }");
    }

    public static string EmitEventProjectionPartial(CandidateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()};");
            sb.AppendLine();
        }

        // Handle nested types by wrapping in containing type declarations
        var containingTypes = GetContainingTypes(info.ClassSymbol);
        foreach (var container in containingTypes)
        {
            sb.AppendLine($"partial {ContainerKeyword(container)} {container.Name}{ContainerTypeParams(container)}");
            sb.AppendLine("{");
        }

        var className = info.ClassSymbol.Name;

        // Include type parameters if the class is generic
        var typeParams = "";
        if (info.ClassSymbol.TypeParameters.Length > 0)
        {
            typeParams = "<" + string.Join(", ", info.ClassSymbol.TypeParameters.Select(t => t.Name)) + ">";
        }

        sb.AppendLine($"partial class {className}{typeParams}");
        sb.AppendLine("{");

        // Emit constructor that registers published document types from Create/Transform methods
        EmitEventProjectionConstructor(sb, info, className);

        EmitEventProjectionApplyAsync(sb, info);

        sb.AppendLine("}");

        // Close containing type declarations
        foreach (var _ in containingTypes)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits a partial class with only a constructor that registers published document types.
    /// Used for EventProjection subclasses that have an explicit ApplyAsync override and
    /// call Store/Insert/Delete with document types that need to be registered.
    /// See https://github.com/JasperFx/marten/issues/4166
    /// </summary>
    public static string EmitEventProjectionTypeRegistrationPartial(CandidateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()};");
            sb.AppendLine();
        }

        // Handle nested types
        var containingTypes = GetContainingTypes(info.ClassSymbol);
        foreach (var container in containingTypes)
        {
            sb.AppendLine($"partial {ContainerKeyword(container)} {container.Name}{ContainerTypeParams(container)}");
            sb.AppendLine("{");
        }

        var className = info.ClassSymbol.Name;

        var typeParams = "";
        if (info.ClassSymbol.TypeParameters.Length > 0)
        {
            typeParams = "<" + string.Join(", ", info.ClassSymbol.TypeParameters.Select(t => t.Name)) + ">";
        }

        sb.AppendLine($"partial class {className}{typeParams}");
        sb.AppendLine("{");

        if (!info.HasExistingParameterlessConstructor && info.DiscoveredPublishedTypes.Count > 0)
        {
            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
            sb.AppendLine($"    public {className}()");
            sb.AppendLine("    {");
            foreach (var docType in info.DiscoveredPublishedTypes.Select(t => Fqn(t)).Distinct())
            {
                sb.AppendLine($"        RegisterPublishedType(typeof({docType}));");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        foreach (var _ in containingTypes)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static List<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol type)
    {
        var result = new List<INamedTypeSymbol>();
        var current = type.ContainingType;
        while (current != null)
        {
            result.Add(current);
            current = current.ContainingType;
        }

        result.Reverse(); // Outermost first
        return result;
    }

    /// <summary>
    /// Emits a constructor that registers document types published by Create/Transform methods
    /// as published types, so that the document storage is generated for code-gen scenarios.
    /// See https://github.com/JasperFx/marten/issues/4166
    /// </summary>
    private static void EmitEventProjectionConstructor(StringBuilder sb, CandidateInfo info, string className)
    {
        // Skip if the class already has an explicit parameterless constructor
        if (info.HasExistingParameterlessConstructor) return;

        // Collect distinct entity return types from Create/Transform methods
        var publishedTypes = info.Methods
            .Where(m => m.EntityReturnType != null && (m.MethodName == "Create" || m.MethodName == "Transform"))
            .Select(m => Fqn(m.EntityReturnType!))
            .Distinct()
            .ToList();

        if (publishedTypes.Count == 0) return;

        sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
        sb.AppendLine($"    public {className}()");
        sb.AppendLine("    {");
        foreach (var typeName in publishedTypes)
        {
            sb.AppendLine($"        RegisterPublishedType(typeof({typeName}));");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitEventProjectionApplyAsync(StringBuilder sb, CandidateInfo info)
    {
        var operationsType = Fqn(info.OperationsType!);
        var hasAnyAsync = info.HasAnyAsync;

        // Sort methods so that derived event types come before base event types
        // to avoid unreachable switch case errors
        var sortedMethods = info.Methods
            .OrderByDescending(m => GetTypeDepth(m.EventType))
            .ToList();

        if (hasAnyAsync)
        {
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
            sb.AppendLine($"    public override async global::System.Threading.Tasks.ValueTask ApplyAsync(");
            sb.AppendLine($"        {operationsType} operations,");
            sb.AppendLine($"        global::JasperFx.Events.IEvent e,");
            sb.AppendLine($"        global::System.Threading.CancellationToken cancellation)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (e.Data)");
            sb.AppendLine("        {");

            foreach (var method in sortedMethods)
            {
                EmitEventProjectionCase(sb, method, operationsType, true);
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
            sb.AppendLine($"    public override global::System.Threading.Tasks.ValueTask ApplyAsync(");
            sb.AppendLine($"        {operationsType} operations,");
            sb.AppendLine($"        global::JasperFx.Events.IEvent e,");
            sb.AppendLine($"        global::System.Threading.CancellationToken cancellation)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (e.Data)");
            sb.AppendLine("        {");

            foreach (var method in sortedMethods)
            {
                EmitEventProjectionCase(sb, method, operationsType, false);
            }

            sb.AppendLine("        }");
            sb.AppendLine("        return new global::System.Threading.Tasks.ValueTask();");
            sb.AppendLine("    }");
        }
    }

    /// <summary>
    /// Picks one handler per event type so the generated switch doesn't emit
    /// duplicate arms (CS8120). When the SG discovers both a projection-side
    /// handler (e.g. `Bug4268ProductProjection.Apply(EventX, AggregateY)`)
    /// AND an aggregate-side handler for the same event type (e.g.
    /// `Bug4268Product.Apply(EventX)`), the projection-side handler wins —
    /// the projection's method typically wraps / extends the aggregate's
    /// behavior and is the user's intentional dispatch entry point. Ties on
    /// IsOnAggregate break to the overload with more parameters (the more
    /// specific signature). Final ordering puts more-derived event types
    /// first so interface arms don't shadow concrete-class arms.
    /// </summary>
    private static List<ConventionalMethodInfo> CoalesceByEventType(IEnumerable<ConventionalMethodInfo> methods)
    {
        return methods
            .GroupBy<ConventionalMethodInfo, ITypeSymbol>(m => m.EventType, SymbolEqualityComparer.Default)
            .Select(g => g
                .OrderBy(m => m.IsOnAggregate)
                .ThenByDescending(m => m.Symbol.Parameters.Length)
                .First())
            .OrderByDescending(m => GetTypeDepth(m.EventType))
            .ToList();
    }

    private static int GetTypeDepth(ITypeSymbol type)
    {
        // Used to order `switch (e.Data)` arms so that more-derived types come
        // before their base types / interfaces. C# pattern matching falls
        // through to the first satisfied case; if `case IBase data` is emitted
        // before `case Concrete data` and Concrete : IBase, the compiler flags
        // the latter as unreachable (CS8120).
        //
        // Interfaces are pushed below every concrete class (negative key) so
        // an interface arm always sinks below any class arm — including arms
        // for classes that *don't* implement the interface, which is fine
        // because order among unrelated types doesn't matter to correctness.
        // Among interfaces, ones that extend more other interfaces sort first.
        if (type.TypeKind == TypeKind.Interface)
        {
            return -1_000_000 + type.AllInterfaces.Length;
        }

        int depth = 0;
        var current = type.BaseType;
        while (current != null)
        {
            depth++;
            current = current.BaseType;
        }

        return depth;
    }

    private static void EmitEventProjectionCase(StringBuilder sb, ConventionalMethodInfo method,
        string operationsType, bool isAsyncContext)
    {
        var eventTypeName = Fqn(method.EventType);

        if (method.UsesIEventWrapper)
        {
            sb.AppendLine($"            case {eventTypeName}:");
        }
        else
        {
            sb.AppendLine($"            case {eventTypeName} data:");
        }

        if (method.MethodName == "Project")
        {
            EmitEventProjectionProjectCall(sb, method, isAsyncContext);
        }
        else // Create or Transform
        {
            EmitEventProjectionCreateCall(sb, method, isAsyncContext);
        }

        sb.AppendLine("                break;");
    }

    private static void EmitEventProjectionProjectCall(StringBuilder sb, ConventionalMethodInfo method,
        bool isAsyncContext)
    {
        var args = BuildEventProjectionArgs(method);

        if (method.IsAsync && isAsyncContext)
        {
            sb.AppendLine($"                await {method.MethodName}({args});");
        }
        else
        {
            sb.AppendLine($"                {method.MethodName}({args});");
        }
    }

    private static void EmitEventProjectionCreateCall(StringBuilder sb, ConventionalMethodInfo method,
        bool isAsyncContext)
    {
        var args = BuildEventProjectionArgs(method);

        if (method.IsAsync && isAsyncContext)
        {
            sb.AppendLine($"                storeEntity(operations, await {method.MethodName}({args}));");
        }
        else
        {
            sb.AppendLine($"                storeEntity(operations, {method.MethodName}({args}));");
        }
    }

    private static string BuildEventProjectionArgs(ConventionalMethodInfo method)
    {
        var parts = new List<string>();
        var parameters = method.Symbol.Parameters;

        foreach (var param in parameters)
        {
            var paramType = param.Type;

            if (method.UsesIEventWrapper && IsIEventGenericWrapper(paramType))
            {
                var innerType = Fqn(((INamedTypeSymbol)paramType).TypeArguments[0]);
                parts.Add($"(global::JasperFx.Events.IEvent<{innerType}>)e");
            }
            else if (IsRawIEvent(paramType))
            {
                parts.Add("e");
            }
            else if (IsCancellationToken(paramType))
            {
                parts.Add("cancellation");
            }
            else if (IsEventDataType(paramType, method))
            {
                if (method.UsesIEventWrapper)
                {
                    parts.Add($"(({Fqn(paramType)})e.Data)");
                }
                else
                {
                    parts.Add("data");
                }
            }
            else
            {
                // Assume it's the operations type
                parts.Add("operations");
            }
        }

        return string.Join(", ", parts);
    }

    public static string EmitSelfAggregatingEvolver(CandidateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var aggregateFullName = Fqn(info.AggregateType!);
        var idFullName = Fqn(info.IdentityType!);
        var evolverName = BuildUniqueEvolverName(info, "Evolver");

        // Assembly attributes must precede namespace declarations
        sb.AppendLine($"[assembly: global::JasperFx.Events.Aggregation.GeneratedEvolver(typeof({aggregateFullName}), typeof({GetFullyQualifiedEvolverName(info, evolverName)}))]");
        if (info.HasNaturalKey)
        {
            sb.AppendLine($"[assembly: global::JasperFx.Events.Aggregation.NaturalKeyAggregate(typeof({aggregateFullName}))]");
        }
        sb.AppendLine();

        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()};");
            sb.AppendLine();
        }

        if (info.HasShouldDelete)
        {
            sb.AppendLine($"internal sealed class {evolverName} : global::JasperFx.Events.Aggregation.IGeneratedSyncDetermineAction<{aggregateFullName}, {idFullName}>");
            sb.AppendLine("{");
            EmitEventTypesProperty(sb, info);
            sb.AppendLine();
            EmitSelfAggregatingDetermineAction(sb, info, aggregateFullName, idFullName);
        }
        else
        {
            sb.AppendLine($"internal sealed class {evolverName} : global::JasperFx.Events.Aggregation.IGeneratedSyncEvolver<{aggregateFullName}, {idFullName}>");
            sb.AppendLine("{");
            EmitEventTypesProperty(sb, info);
            sb.AppendLine();
            EmitSelfAggregatingEvolve(sb, info, aggregateFullName, idFullName);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits an evolver class for a self-aggregating type that has an Evolve or EvolveAsync method.
    /// The generated class implements IGeneratedSyncEvolver or IGeneratedAsyncEvolver and
    /// delegates to the user's Evolve/EvolveAsync method.
    /// </summary>
    public static string EmitSelfAggregatingEvolveEvolver(CandidateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var evolve = info.EvolveMethod!;
        var aggregateFullName = Fqn(info.AggregateType!);
        var idFullName = Fqn(info.IdentityType!);
        var evolverName = BuildUniqueEvolverName(info, "EvolveEvolver");

        // Assembly attribute for discovery
        sb.AppendLine($"[assembly: global::JasperFx.Events.Aggregation.GeneratedEvolver(typeof({aggregateFullName}), typeof({GetFullyQualifiedEvolverName(info, evolverName)}))]");
        if (info.HasNaturalKey)
        {
            sb.AppendLine($"[assembly: global::JasperFx.Events.Aggregation.NaturalKeyAggregate(typeof({aggregateFullName}))]");
        }
        sb.AppendLine();

        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()};");
            sb.AppendLine();
        }

        var isAsync = evolve.IsAsync || evolve.HasSession;
        string interfaceName;

        if (isAsync)
        {
            interfaceName = $"global::JasperFx.Events.Aggregation.IGeneratedAsyncEvolver<{aggregateFullName}, {idFullName}>";
        }
        else
        {
            interfaceName = $"global::JasperFx.Events.Aggregation.IGeneratedSyncEvolver<{aggregateFullName}, {idFullName}>";
        }

        sb.AppendLine($"internal sealed class {evolverName} : {interfaceName}");
        sb.AppendLine("{");

        // Emit EventTypes property
        EmitEvolveEventTypesProperty(sb, evolve);
        sb.AppendLine();

        // Emit the Evolve or EvolveAsync method
        if (isAsync)
        {
            EmitAsyncEvolveMethod(sb, evolve, aggregateFullName, idFullName);
        }
        else
        {
            EmitSyncEvolveMethod(sb, evolve, aggregateFullName, idFullName);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitEvolveEventTypesProperty(StringBuilder sb, EvolveMethodInfo evolve)
    {
        if (evolve.ExtractedEventTypes.Count > 0)
        {
            var types = evolve.ExtractedEventTypes.Select(t => Fqn(t)).Distinct().ToList();
            sb.Append("    public global::System.Type[] EventTypes => [");
            sb.Append(string.Join(", ", types.Select(t => $"typeof({t})")));
            sb.AppendLine("];");
        }
        else
        {
            // No types extracted — empty array means no filtering
            sb.AppendLine("    public global::System.Type[] EventTypes => [];");
        }
    }

    private static void EmitSyncEvolveMethod(StringBuilder sb, EvolveMethodInfo evolve,
        string docType, string idType)
    {
        sb.AppendLine($"    public {docType}? Evolve({docType}? snapshot, {idType} id, global::JasperFx.Events.IEvent e)");
        sb.AppendLine("    {");

        if (evolve.IsMutable)
        {
            // void Evolve(object) or void Evolve(IEvent)
            sb.AppendLine($"        snapshot ??= new {docType}();");
            if (evolve.TakesIEvent)
            {
                sb.AppendLine("        snapshot.Evolve(e);");
            }
            else
            {
                sb.AppendLine("        snapshot.Evolve(e.Data);");
            }
            sb.AppendLine("        return snapshot;");
        }
        else
        {
            // TDoc Evolve(object) or TDoc Evolve(IEvent)
            if (evolve.TakesIEvent)
            {
                sb.AppendLine($"        return (snapshot ?? new {docType}()).Evolve(e);");
            }
            else
            {
                sb.AppendLine($"        return (snapshot ?? new {docType}()).Evolve(e.Data);");
            }
        }

        sb.AppendLine("    }");
    }

    private static void EmitAsyncEvolveMethod(StringBuilder sb, EvolveMethodInfo evolve,
        string docType, string idType)
    {
        sb.AppendLine($"    public async global::System.Threading.Tasks.ValueTask<{docType}?> EvolveAsync(");
        sb.AppendLine($"        {docType}? snapshot, {idType} id, global::JasperFx.Events.IEvent e,");
        sb.AppendLine("        object session, global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");

        // Build the method call arguments
        var args = new List<string>();
        if (evolve.TakesIEvent)
            args.Add("e");
        else
            args.Add("e.Data");

        if (evolve.HasSession)
        {
            // Cast the session parameter to the user's declared session type
            var sessionParam = evolve.Symbol.Parameters.FirstOrDefault(p =>
                IsQuerySession(p.Type));
            var sessionTypeName = sessionParam != null
                ? Fqn(sessionParam.Type)
                : "object";
            args.Add($"({sessionTypeName})session");
        }

        if (evolve.HasCancellationToken)
            args.Add("ct");

        var argsStr = string.Join(", ", args);
        var methodName = evolve.Symbol.Name; // "Evolve" or "EvolveAsync"

        if (evolve.IsMutable)
        {
            sb.AppendLine($"        snapshot ??= new {docType}();");
            sb.AppendLine($"        await snapshot.{methodName}({argsStr});");
            sb.AppendLine("        return snapshot;");
        }
        else
        {
            sb.AppendLine($"        return await (snapshot ?? new {docType}()).{methodName}({argsStr});");
        }

        sb.AppendLine("    }");
    }

    private static bool IsQuerySession(ITypeSymbol type)
    {
        var name = type.ToDisplayString();
        return name.EndsWith("IQuerySession") || name.EndsWith("QuerySession");
    }

    /// <summary>
    /// Builds an evolver class name that includes the parent-type chain so two
    /// aggregates with the same simple name (e.g. `Bug_2666.CounterWithCreate`
    /// and `Bug_2528.CounterWithCreate`, common in xUnit test files where the
    /// aggregate is nested inside the test class) don't collide on the
    /// generated `CounterWithCreateEvolver` class name in the shared namespace.
    /// See #297.
    /// </summary>
    private static string BuildUniqueEvolverName(CandidateInfo info, string suffix)
    {
        var prefix = new StringBuilder();
        for (INamedTypeSymbol? container = info.ClassSymbol.ContainingType;
             container is not null;
             container = container.ContainingType)
        {
            prefix.Insert(0, container.Name + "_");
        }

        // When the same aggregate type can be registered against multiple
        // stream-identity types (e.g. `AggregateStreamAsync<CountOfLetters>`
        // with both Guid and string stream IDs), emit a separate evolver per
        // TId. Append a sanitized TId tag in the name so the two evolvers
        // don't collide in the same namespace. Only needed when the aggregate
        // *itself* doesn't determine TId via an Id property — when it does,
        // Pipeline 1 emits a single dispatcher per TDoc and existing tests
        // (and downstream consumers) reference the original
        // `{Name}Evolver` class name. See #297.
        var idTag = "";
        if (info.IdentityType is { } id && !AggregateHasOwnIdentity(info))
        {
            var idName = id.Name;
            if (!string.IsNullOrEmpty(idName))
                idTag = "_" + idName.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");
        }

        return prefix.ToString() + info.ClassSymbol.Name + idTag + suffix;
    }

    /// <summary>
    /// True when the aggregate type itself locks in the TId (via an Id property
    /// or [AggregateIdentity] attribute). False when the candidate's TId came
    /// from a Pipeline 3 call-site hint and could conceivably vary by call site.
    /// </summary>
    private static bool AggregateHasOwnIdentity(CandidateInfo info)
    {
        if (info.AggregateType is null) return false;

        for (INamedTypeSymbol? current = info.AggregateType;
             current is not null && current.SpecialType != SpecialType.System_Object;
             current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol prop && prop.Name == "Id")
                    return true;
            }

            foreach (var attr in current.GetAttributes())
            {
                if (attr.AttributeClass?.Name is "AggregateIdentityAttribute" or "AggregateIdentity")
                    return true;
            }
        }

        return false;
    }

    private static string GetFullyQualifiedEvolverName(CandidateInfo info, string evolverName)
    {
        var ns = info.ClassSymbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
            return $"global::{ns.ToDisplayString()}.{evolverName}";
        return $"global::{evolverName}";
    }

    private static void EmitEventTypesProperty(StringBuilder sb, CandidateInfo info)
    {
        var eventTypes = info.Methods.Select(m => Fqn(m.EventType)).Distinct().ToList();
        sb.Append("    public global::System.Type[] EventTypes => [");
        sb.Append(string.Join(", ", eventTypes.Select(t => $"typeof({t})")));
        sb.AppendLine("];");
    }

    // --- Partial projection: Evolve (all sync, no ShouldDelete) ---

    private static void EmitEvolveOverride(StringBuilder sb, CandidateInfo info)
    {
        var docType = Fqn(info.AggregateType!);
        var idType = Fqn(info.IdentityType!);

        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
        sb.AppendLine($"    public override {docType}? Evolve({docType}? snapshot, {idType} id, global::JasperFx.Events.IEvent e)");
        sb.AppendLine("    {");

        var createMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Create"));
        var applyMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Apply"));

        // Null snapshot branch
        sb.AppendLine("        if (snapshot == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (e.Data)");
        sb.AppendLine("            {");
        EmitNullSnapshotCases(sb, info, createMethods, applyMethods, "                ");
        sb.AppendLine("                default: return null;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Non-null snapshot branch
        sb.AppendLine("        switch (e.Data)");
        sb.AppendLine("        {");
        EmitNonNullSnapshotCases(sb, info, applyMethods, "            ");
        sb.AppendLine("            default: return snapshot;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }

    // --- Partial projection: EvolveAsync (mixed sync/async, no ShouldDelete) ---

    private static void EmitEvolveAsyncOverride(StringBuilder sb, CandidateInfo info)
    {
        var docType = Fqn(info.AggregateType!);
        var idType = Fqn(info.IdentityType!);
        var sessionType = info.QuerySessionType is { } qs ? Fqn(qs) : "object";

        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
        sb.AppendLine($"    public override async global::System.Threading.Tasks.ValueTask<{docType}?> EvolveAsync(");
        sb.AppendLine($"        {docType}? snapshot, {idType} id, {sessionType} session,");
        sb.AppendLine($"        global::JasperFx.Events.IEvent e, global::System.Threading.CancellationToken cancellation)");
        sb.AppendLine("    {");

        var createMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Create"));
        var applyMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Apply"));

        sb.AppendLine("        if (snapshot == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (e.Data)");
        sb.AppendLine("            {");
        EmitNullSnapshotCasesAsync(sb, info, createMethods, applyMethods, "                ");
        sb.AppendLine("                default: return null;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        switch (e.Data)");
        sb.AppendLine("        {");
        EmitNonNullSnapshotCasesAsync(sb, info, applyMethods, "            ");
        sb.AppendLine("            default: return snapshot;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }

    // --- Partial projection: DetermineActionAsync (has ShouldDelete) ---

    private static void EmitDetermineActionAsyncOverride(StringBuilder sb, CandidateInfo info)
    {
        var docType = Fqn(info.AggregateType!);
        var idType = Fqn(info.IdentityType!);
        var sessionType = info.QuerySessionType is { } qs ? Fqn(qs) : "object";

        var isAsync = info.HasAnyAsync;
        var asyncKeyword = isAsync ? "async " : "";

        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"JasperFx.Events.SourceGenerator\", \"1.0\")]");
        sb.AppendLine($"    public override {asyncKeyword}global::System.Threading.Tasks.ValueTask<({docType}?, global::JasperFx.Events.Daemon.ActionType)> DetermineActionAsync(");
        sb.AppendLine($"        {sessionType} session,");
        sb.AppendLine($"        {docType}? snapshot,");
        sb.AppendLine($"        {idType} identity,");
        sb.AppendLine($"        global::JasperFx.Events.Aggregation.IIdentitySetter<{docType}, {idType}> identitySetter,");
        sb.AppendLine($"        global::System.Collections.Generic.IReadOnlyList<global::JasperFx.Events.IEvent> events,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellation)");
        sb.AppendLine("    {");
        sb.AppendLine("        var exists = snapshot != null;");
        sb.AppendLine("        foreach (var e in events)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (e.Data)");
        sb.AppendLine("            {");

        // ShouldDelete cases first — coalesce overloads sharing the same event
        // type into a single switch arm so the compiler doesn't flag duplicate
        // arms as unreachable (CS8120). Multiple ShouldDelete overloads on the
        // same event type are OR'd together so the snapshot is dropped if any
        // overload returns true.
        var shouldDeleteMethods = info.Methods.Where(m => m.MethodName == "ShouldDelete").ToList();
        var shouldDeleteByEventType = shouldDeleteMethods
            .GroupBy<ConventionalMethodInfo, ITypeSymbol>(m => m.EventType, SymbolEqualityComparer.Default)
            .OrderByDescending(g => GetTypeDepth(g.Key))
            .ToList();
        foreach (var group in shouldDeleteByEventType)
        {
            var eventTypeName = Fqn(group.Key);
            var dataVar = "data";
            sb.AppendLine($"                case {eventTypeName} {dataVar}:");
            sb.Append("                    if (snapshot != null && (");
            bool first = true;
            foreach (var method in group)
            {
                if (!first) sb.Append(" || ");
                first = false;
                EmitShouldDeleteCall(sb, method, dataVar);
            }
            sb.AppendLine("))");
            sb.AppendLine("                        snapshot = null;");
            sb.AppendLine("                    break;");
        }

        // Create cases — coalesce by event type, prefer projection-defined over aggregate-defined.
        var createMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Create"));
        foreach (var method in createMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            sb.AppendLine($"                case {eventTypeName} data when snapshot == null:");
            sb.Append("                    snapshot = ");
            EmitCreateCall(sb, method, "data", "e", isAsync);
            sb.AppendLine(";");
            sb.AppendLine("                    break;");
        }

        // Apply cases — coalesce by event type.
        var applyMethods = CoalesceByEventType(info.Methods.Where(m => m.MethodName == "Apply"));
        foreach (var method in applyMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            // For apply methods where there's no create, we need to handle null snapshot
            bool hasCreateForType = createMethods.Any(c =>
                SymbolEqualityComparer.Default.Equals(c.EventType, method.EventType));

            if (hasCreateForType)
            {
                // Apply only when snapshot exists
                sb.AppendLine($"                case {eventTypeName} data when snapshot != null:");
            }
            else if (info.HasDefaultConstructor)
            {
                sb.AppendLine($"                case {eventTypeName} data:");
                sb.AppendLine($"                    snapshot ??= new {Fqn(info.AggregateType!)}();");
            }
            else
            {
                sb.AppendLine($"                case {eventTypeName} data when snapshot != null:");
            }

            sb.Append("                    ");
            EmitApplyCallStatement(sb, method, "data", "e", isAsync);
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (snapshot == null)");
        if (!isAsync)
        {
            // Sync-path DetermineActionAsync returns ValueTask<(...)> directly; wrap the tuple.
            sb.AppendLine($"            return exists ? new global::System.Threading.Tasks.ValueTask<({docType}?, global::JasperFx.Events.Daemon.ActionType)>((null, global::JasperFx.Events.Daemon.ActionType.Delete)) : new global::System.Threading.Tasks.ValueTask<({docType}?, global::JasperFx.Events.Daemon.ActionType)>((null, global::JasperFx.Events.Daemon.ActionType.Nothing));");
            sb.AppendLine($"        return new global::System.Threading.Tasks.ValueTask<({docType}?, global::JasperFx.Events.Daemon.ActionType)>((snapshot, global::JasperFx.Events.Daemon.ActionType.Store));");
        }
        else
        {
            // Async method body — bare tuple is implicitly wrapped by the async state machine.
            sb.AppendLine($"            return exists ? (null, global::JasperFx.Events.Daemon.ActionType.Delete) : (null, global::JasperFx.Events.Daemon.ActionType.Nothing);");
            sb.AppendLine($"        return (snapshot, global::JasperFx.Events.Daemon.ActionType.Store);");
        }
        sb.AppendLine("    }");
    }

    // --- Self-aggregating: Evolve (sync, no ShouldDelete) ---

    private static void EmitSelfAggregatingEvolve(StringBuilder sb, CandidateInfo info, string docType,
        string idType)
    {
        sb.AppendLine(
            $"    public {docType}? Evolve({docType}? snapshot, {idType} id, global::JasperFx.Events.IEvent e)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (e.Data)");
        sb.AppendLine("        {");

        var createMethods = info.Methods.Where(m => m.MethodName == "Create").ToList();
        var applyMethods = info.Methods.Where(m => m.MethodName == "Apply").ToList();

        // Each event type gets one case. Sort more-derived types first so
        // `case IBase data:` doesn't shadow `case Concrete data:` (CS8120).
        var allEventTypes = info.Methods
            .Select(m => m.EventType)
            .Distinct<ITypeSymbol>(SymbolEqualityComparer.Default)
            .OrderByDescending(t => GetTypeDepth(t!))
            .ToList();

        foreach (var eventType in allEventTypes)
        {
            var eventTypeName = Fqn(eventType!);
            var creates = createMethods.Where(m =>
                SymbolEqualityComparer.Default.Equals(m.EventType, eventType)).ToList();
            var applies = applyMethods.Where(m =>
                SymbolEqualityComparer.Default.Equals(m.EventType, eventType)).ToList();

            sb.AppendLine($"            case {eventTypeName} data:");

            if (creates.Count > 0)
            {
                var create = creates[0];
                sb.AppendLine("                if (snapshot == null)");
                sb.Append("                    snapshot = ");
                EmitSelfAggregatingCreateCall(sb, create, "data");
                sb.AppendLine(";");

                if (applies.Count > 0)
                {
                    sb.AppendLine("                else");
                    sb.Append("                    ");
                    EmitSelfAggregatingApplyCall(sb, applies[0], "data");
                }
            }
            else if (applies.Count > 0)
            {
                if (info.HasDefaultConstructor)
                {
                    sb.AppendLine($"                snapshot ??= new {docType}();");
                }
                else
                {
                    sb.AppendLine("                if (snapshot == null) return null;");
                }

                sb.Append("                ");
                EmitSelfAggregatingApplyCall(sb, applies[0], "data");
            }

            sb.AppendLine("                return snapshot;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                return snapshot;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // --- Self-aggregating: DetermineAction (sync, with ShouldDelete) ---

    private static void EmitSelfAggregatingDetermineAction(StringBuilder sb, CandidateInfo info, string docType,
        string idType)
    {
        sb.AppendLine(
            $"    public ({docType}?, global::JasperFx.Events.Daemon.ActionType) DetermineAction({docType}? snapshot, {idType} id, global::System.Collections.Generic.IReadOnlyList<global::JasperFx.Events.IEvent> events)");
        sb.AppendLine("    {");
        sb.AppendLine("        var exists = snapshot != null;");
        sb.AppendLine("        foreach (var e in events)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (e.Data)");
        sb.AppendLine("            {");

        // ShouldDelete - set snapshot to null and continue processing (allows re-creation)
        var shouldDeleteMethods = info.Methods.Where(m => m.MethodName == "ShouldDelete").ToList();
        foreach (var method in shouldDeleteMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            sb.AppendLine($"                case {eventTypeName} data:");
            sb.Append("                    if (snapshot != null && ");
            EmitSelfAggregatingShouldDeleteCall(sb, method, "data");
            sb.AppendLine(")");
            sb.AppendLine("                        snapshot = null;");
            sb.AppendLine("                    break;");
        }

        // Create + Apply
        var createMethods = info.Methods.Where(m => m.MethodName == "Create").ToList();
        var applyMethods = info.Methods.Where(m => m.MethodName == "Apply").ToList();

        // Group by event type (excluding ShouldDelete events already handled)
        var handledDeleteTypes = new HashSet<ITypeSymbol>(shouldDeleteMethods.Select(m => m.EventType),
            SymbolEqualityComparer.Default);

        var applyAndCreateTypes = info.Methods
            .Where(m => m.MethodName != "ShouldDelete")
            .Select(m => m.EventType)
            .Distinct<ITypeSymbol>(SymbolEqualityComparer.Default)
            .Where(t => !handledDeleteTypes.Contains(t!))
            .OrderByDescending(t => GetTypeDepth(t!))
            .ToList();

        foreach (var eventType in applyAndCreateTypes)
        {
            var eventTypeName = Fqn(eventType!);
            var creates = createMethods.Where(m =>
                SymbolEqualityComparer.Default.Equals(m.EventType, eventType)).ToList();
            var applies = applyMethods.Where(m =>
                SymbolEqualityComparer.Default.Equals(m.EventType, eventType)).ToList();

            sb.AppendLine($"                case {eventTypeName} data:");

            if (creates.Count > 0)
            {
                var create = creates[0];
                sb.AppendLine("                    if (snapshot == null)");
                sb.Append("                        snapshot = ");
                EmitSelfAggregatingCreateCall(sb, create, "data");
                sb.AppendLine(";");

                if (applies.Count > 0)
                {
                    sb.AppendLine("                    else");
                    sb.Append("                        ");
                    EmitSelfAggregatingApplyCall(sb, applies[0], "data");
                }
            }
            else if (applies.Count > 0)
            {
                if (info.HasDefaultConstructor)
                {
                    sb.AppendLine(
                        $"                    snapshot ??= new {Fqn(info.AggregateType!)}();");
                }
                else
                {
                    sb.AppendLine("                    if (snapshot == null) break;");
                }

                sb.Append("                    ");
                EmitSelfAggregatingApplyCall(sb, applies[0], "data");
            }

            sb.AppendLine("                    break;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (snapshot == null)");
        sb.AppendLine(
            "            return exists ? (null, global::JasperFx.Events.Daemon.ActionType.Delete) : (null, global::JasperFx.Events.Daemon.ActionType.Nothing);");
        sb.AppendLine($"        return (snapshot, global::JasperFx.Events.Daemon.ActionType.Store);");
        sb.AppendLine("    }");
    }

    // --- Null snapshot case generation (sync) ---

    private static void EmitNullSnapshotCases(StringBuilder sb, CandidateInfo info,
        List<ConventionalMethodInfo> createMethods, List<ConventionalMethodInfo> applyMethods, string indent)
    {
        // For each event type with a Create method
        foreach (var method in createMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            if (method.UsesIEventWrapper)
            {
                sb.AppendLine($"{indent}case {eventTypeName}:");
                sb.Append($"{indent}    return ");
                EmitCreateCallSync(sb, method, null, "e");
            }
            else
            {
                sb.AppendLine($"{indent}case {eventTypeName} data:");
                sb.Append($"{indent}    return ");
                EmitCreateCallSync(sb, method, "data", "e");
            }

            sb.AppendLine(";");
        }

        // For Apply-only event types (no matching Create), use default ctor + Apply
        var createEventTypes = new HashSet<ITypeSymbol>(createMethods.Select(m => m.EventType),
            SymbolEqualityComparer.Default);

        foreach (var method in applyMethods)
        {
            if (createEventTypes.Contains(method.EventType)) continue;

            var eventTypeName = Fqn(method.EventType);
            var docType = Fqn(info.AggregateType!);

            if (!info.HasDefaultConstructor) continue; // Can't create without constructor

            if (method.UsesIEventWrapper)
            {
                sb.AppendLine($"{indent}case {eventTypeName}:");
            }
            else
            {
                sb.AppendLine($"{indent}case {eventTypeName} data:");
            }

            if (method.IsVoid && !method.ReturnsAggregate)
            {
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var s = new {docType}();");
                sb.Append($"{indent}    ");
                EmitApplyCallExpression(sb, method, method.UsesIEventWrapper ? null : "data", "e", false, "s");
                sb.AppendLine(";");
                sb.AppendLine($"{indent}    return s;");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                // Returns aggregate - pass new instance
                sb.Append($"{indent}    return ");
                EmitApplyCallExpression(sb, method, method.UsesIEventWrapper ? null : "data", "e", false, $"new {docType}()");
                sb.AppendLine(";");
            }
        }
    }

    // --- Null snapshot case generation (async) ---

    private static void EmitNullSnapshotCasesAsync(StringBuilder sb, CandidateInfo info,
        List<ConventionalMethodInfo> createMethods, List<ConventionalMethodInfo> applyMethods, string indent)
    {
        foreach (var method in createMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            if (method.UsesIEventWrapper)
            {
                sb.AppendLine($"{indent}case {eventTypeName}:");
                sb.Append($"{indent}    return ");
            }
            else
            {
                sb.AppendLine($"{indent}case {eventTypeName} data:");
                sb.Append($"{indent}    return ");
            }

            EmitCreateCall(sb, method, method.UsesIEventWrapper ? null : "data", "e", true);
            sb.AppendLine(";");
        }

        var createEventTypes = new HashSet<ITypeSymbol>(createMethods.Select(m => m.EventType),
            SymbolEqualityComparer.Default);

        foreach (var method in applyMethods)
        {
            if (createEventTypes.Contains(method.EventType)) continue;
            if (!info.HasDefaultConstructor) continue;

            var eventTypeName = Fqn(method.EventType);
            var docType = Fqn(info.AggregateType!);

            sb.AppendLine($"{indent}case {eventTypeName} data:");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    var s = new {docType}();");
            var awaitPrefix = method.IsAsync ? "await " : "";
            sb.Append($"{indent}    {awaitPrefix}");
            EmitApplyCallExpression(sb, method, "data", "e", true, "s");
            sb.AppendLine(";");
            sb.AppendLine($"{indent}    return s;");
            sb.AppendLine($"{indent}}}");
        }
    }

    // --- Non-null snapshot case generation (sync) ---

    private static void EmitNonNullSnapshotCases(StringBuilder sb, CandidateInfo info,
        List<ConventionalMethodInfo> applyMethods, string indent)
    {
        foreach (var method in applyMethods)
        {
            var eventTypeName = Fqn(method.EventType);

            if (method.UsesIEventWrapper)
            {
                sb.AppendLine($"{indent}case {eventTypeName}:");
            }
            else
            {
                sb.AppendLine($"{indent}case {eventTypeName} data:");
            }

            if (method.IsVoid && !method.ReturnsAggregate)
            {
                sb.Append($"{indent}    ");
                EmitApplyCallExpression(sb, method, method.UsesIEventWrapper ? null : "data", "e", false);
                sb.AppendLine(";");
                sb.AppendLine($"{indent}    return snapshot;");
            }
            else
            {
                sb.Append($"{indent}    return ");
                EmitApplyCallExpression(sb, method, method.UsesIEventWrapper ? null : "data", "e", false);
                sb.AppendLine(";");
            }
        }
    }

    // --- Non-null snapshot case generation (async) ---

    private static void EmitNonNullSnapshotCasesAsync(StringBuilder sb, CandidateInfo info,
        List<ConventionalMethodInfo> applyMethods, string indent)
    {
        foreach (var method in applyMethods)
        {
            var eventTypeName = Fqn(method.EventType);
            sb.AppendLine($"{indent}case {eventTypeName} data:");

            if (method.IsAsync)
            {
                if (method.ReturnsAggregate)
                {
                    sb.Append($"{indent}    return await ");
                    EmitApplyCallExpression(sb, method, "data", "e", true);
                    sb.AppendLine(";");
                }
                else
                {
                    sb.Append($"{indent}    await ");
                    EmitApplyCallExpression(sb, method, "data", "e", true);
                    sb.AppendLine(";");
                    sb.AppendLine($"{indent}    return snapshot;");
                }
            }
            else
            {
                // Sync method body inside the async dispatch path — `session` and
                // `cancellation` are still in scope from the enclosing
                // EvolveAsync / DetermineActionAsync method, so handler params
                // that need them must still bind correctly. Pass
                // includeSessionAndCancellation=true here. See #297.
                if (method.ReturnsAggregate)
                {
                    sb.Append($"{indent}    return ");
                    EmitApplyCallExpression(sb, method, "data", "e", true);
                    sb.AppendLine(";");
                }
                else
                {
                    sb.Append($"{indent}    ");
                    EmitApplyCallExpression(sb, method, "data", "e", true);
                    sb.AppendLine(";");
                    sb.AppendLine($"{indent}    return snapshot;");
                }
            }
        }
    }

    // --- Call expression helpers ---

    private static void EmitApplyCallExpression(StringBuilder sb, ConventionalMethodInfo method,
        string? dataVar, string eventVar, bool includeSessionAndCancellation, string aggregateVar = "snapshot")
    {
        var args = BuildApplyArgs(method, dataVar, eventVar, includeSessionAndCancellation, aggregateVar);

        if (method.IsOnAggregate)
        {
            sb.Append($"{aggregateVar}.{method.MethodName}({args})");
        }
        else
        {
            sb.Append($"{method.MethodName}({args})");
        }
    }

    private static void EmitCreateCallSync(StringBuilder sb, ConventionalMethodInfo method,
        string? dataVar, string eventVar)
    {
        var args = BuildCreateArgs(method, dataVar, eventVar, false);

        if (method.IsStatic)
        {
            var containingType = Fqn(method.Symbol.ContainingType);
            sb.Append($"{containingType}.{method.MethodName}({args})");
        }
        else if (method.IsOnAggregate)
        {
            // Static create on aggregate
            var containingType = Fqn(method.Symbol.ContainingType);
            sb.Append($"{containingType}.{method.MethodName}({args})");
        }
        else
        {
            sb.Append($"{method.MethodName}({args})");
        }
    }

    private static void EmitCreateCall(StringBuilder sb, ConventionalMethodInfo method,
        string? dataVar, string eventVar, bool isAsync)
    {
        var args = BuildCreateArgs(method, dataVar, eventVar, isAsync);
        var awaitPrefix = method.IsAsync && isAsync ? "await " : "";

        if (method.IsStatic)
        {
            var containingType = Fqn(method.Symbol.ContainingType);
            sb.Append($"{awaitPrefix}{containingType}.{method.MethodName}({args})");
        }
        else if (method.IsOnAggregate)
        {
            var containingType = Fqn(method.Symbol.ContainingType);
            sb.Append($"{awaitPrefix}{containingType}.{method.MethodName}({args})");
        }
        else
        {
            sb.Append($"{awaitPrefix}{method.MethodName}({args})");
        }
    }

    private static void EmitApplyCallStatement(StringBuilder sb, ConventionalMethodInfo method,
        string dataVar, string eventVar, bool isAsync)
    {
        if (method.IsAsync && isAsync)
        {
            if (method.ReturnsAggregate)
            {
                sb.Append("snapshot = await ");
            }
            else
            {
                sb.Append("await ");
            }
        }
        else
        {
            if (method.ReturnsAggregate)
            {
                sb.Append("snapshot = ");
            }
        }

        EmitApplyCallExpression(sb, method, dataVar, eventVar, isAsync);
        sb.AppendLine(";");
    }

    private static void EmitShouldDeleteCall(StringBuilder sb, ConventionalMethodInfo method, string dataVar)
    {
        var args = BuildShouldDeleteArgs(method, dataVar);
        var awaitKeyword = method.IsAsync ? "await " : "";

        if (method.IsOnAggregate)
        {
            sb.Append($"{awaitKeyword}snapshot.{method.MethodName}({args})");
        }
        else
        {
            sb.Append($"{awaitKeyword}{method.MethodName}({args})");
        }
    }

    private static string BuildSelfAggregatingArgs(ConventionalMethodInfo method, string dataVar)
    {
        var parts = new List<string>();
        var parameters = method.Symbol.Parameters;
        var containingType = method.Symbol.ContainingType;

        foreach (var param in parameters)
        {
            var paramType = param.Type;

            if (method.UsesIEventWrapper && IsIEventGenericWrapper(paramType))
            {
                var innerType = Fqn(((INamedTypeSymbol)paramType).TypeArguments[0]);
                parts.Add($"(global::JasperFx.Events.IEvent<{innerType}>)e");
            }
            else if (IsRawIEvent(paramType))
            {
                parts.Add("e");
            }
            else if (SymbolEqualityComparer.Default.Equals(paramType, containingType))
            {
                // The aggregate itself, as a second/third parameter on a self-aggregating
                // Apply/Create/ShouldDelete method — e.g.
                //   public TAgg Apply(SomeEvent e, TAgg current) => ...;
                // The previous emitter unconditionally fell through to `dataVar` for any
                // non-IEvent parameter, generating `snapshot.Apply(data, data)` (CS1503).
                parts.Add("snapshot");
            }
            else if (IsQuerySession(paramType))
            {
                parts.Add("session");
            }
            else if (IsCancellationToken(paramType))
            {
                parts.Add("cancellation");
            }
            else
            {
                // Event data
                parts.Add(dataVar);
            }
        }

        return string.Join(", ", parts);
    }

    private static void EmitSelfAggregatingCreateCall(StringBuilder sb, ConventionalMethodInfo method,
        string dataVar)
    {
        var args = BuildSelfAggregatingArgs(method, dataVar);

        if (method.IsStatic)
        {
            var containingType = Fqn(method.Symbol.ContainingType);
            sb.Append($"{containingType}.{method.MethodName}({args})");
        }
        else
        {
            // Instance Create on aggregate - not typical for self-aggregating
            sb.Append($"snapshot.{method.MethodName}({args})");
        }
    }

    private static void EmitSelfAggregatingApplyCall(StringBuilder sb, ConventionalMethodInfo method,
        string dataVar)
    {
        var args = BuildSelfAggregatingArgs(method, dataVar);

        // Static Apply on a self-aggregating record (e.g.
        //   public static TAgg Apply(SomeEvent e, TAgg current) => ...;
        // ) — must be invoked as Type.Apply(...) not snapshot.Apply(...) (CS0176).
        var receiver = method.IsStatic
            ? Fqn(method.Symbol.ContainingType)
            : "snapshot";

        if (method.ReturnsAggregate)
        {
            sb.AppendLine($"snapshot = {receiver}.{method.MethodName}({args});");
        }
        else
        {
            sb.AppendLine($"{receiver}.{method.MethodName}({args});");
        }
    }

    private static void EmitSelfAggregatingShouldDeleteCall(StringBuilder sb, ConventionalMethodInfo method,
        string dataVar)
    {
        var args = BuildSelfAggregatingArgs(method, dataVar);
        var receiver = method.IsStatic
            ? Fqn(method.Symbol.ContainingType)
            : "snapshot";
        sb.Append($"{receiver}.{method.MethodName}({args})");
    }

    // --- Argument builders ---

    private static string BuildApplyArgs(ConventionalMethodInfo method, string? dataVar, string eventVar,
        bool includeSessionAndCancellation, string aggregateVar = "snapshot")
    {
        var parts = new List<string>();
        var parameters = method.Symbol.Parameters;

        foreach (var param in parameters)
        {
            var paramType = param.Type;

            if (method.UsesIEventWrapper && IsIEventGenericWrapper(paramType))
            {
                var innerType = Fqn(((INamedTypeSymbol)paramType).TypeArguments[0]);
                parts.Add($"(global::JasperFx.Events.IEvent<{innerType}>){eventVar}");
            }
            else if (IsRawIEvent(paramType))
            {
                parts.Add(eventVar);
            }
            else if (IsQuerySession(paramType) && includeSessionAndCancellation)
            {
                parts.Add("session");
            }
            else if (IsCancellationToken(paramType) && includeSessionAndCancellation)
            {
                parts.Add("cancellation");
            }
            else if (IsAggregateParam(paramType, method))
            {
                parts.Add(aggregateVar);
            }
            else
            {
                // Event data
                parts.Add(dataVar ?? $"(({Fqn(paramType)})e.Data)");
            }
        }

        return string.Join(", ", parts);
    }

    private static string BuildCreateArgs(ConventionalMethodInfo method, string? dataVar, string eventVar,
        bool includeSessionAndCancellation)
    {
        var parts = new List<string>();
        var parameters = method.Symbol.Parameters;

        foreach (var param in parameters)
        {
            var paramType = param.Type;

            if (method.UsesIEventWrapper && IsIEventGenericWrapper(paramType))
            {
                var innerType = Fqn(((INamedTypeSymbol)paramType).TypeArguments[0]);
                parts.Add($"(global::JasperFx.Events.IEvent<{innerType}>){eventVar}");
            }
            else if (IsRawIEvent(paramType))
            {
                parts.Add(eventVar);
            }
            else if (IsQuerySession(paramType) && includeSessionAndCancellation)
            {
                parts.Add("session");
            }
            else if (IsCancellationToken(paramType) && includeSessionAndCancellation)
            {
                parts.Add("cancellation");
            }
            else
            {
                // Event data
                parts.Add(dataVar ?? $"(({Fqn(paramType)})e.Data)");
            }
        }

        return string.Join(", ", parts);
    }

    private static string BuildShouldDeleteArgs(ConventionalMethodInfo method, string dataVar)
    {
        var parts = new List<string>();
        var parameters = method.Symbol.Parameters;

        foreach (var param in parameters)
        {
            var paramType = param.Type;

            if (IsAggregateParam(paramType, method))
            {
                parts.Add("snapshot");
            }
            else if (method.UsesIEventWrapper && IsIEventGenericWrapper(paramType))
            {
                var innerType = Fqn(((INamedTypeSymbol)paramType).TypeArguments[0]);
                parts.Add($"(global::JasperFx.Events.IEvent<{innerType}>)e");
            }
            else if (IsRawIEvent(paramType))
            {
                parts.Add("e");
            }
            else if (IsQuerySession(paramType))
            {
                parts.Add("session");
            }
            else if (IsCancellationToken(paramType))
            {
                parts.Add("cancellation");
            }
            else
            {
                parts.Add(dataVar);
            }
        }

        return string.Join(", ", parts);
    }

    private static bool IsAggregateParam(ITypeSymbol paramType, ConventionalMethodInfo method)
    {
        // For projection methods, the aggregate is a parameter
        if (!method.IsOnAggregate)
        {
            // Check if this parameter type matches the aggregate type from the method's context
            // We check by looking at whether the type isn't the event type, IEvent, session, or cancellation token
            return !SymbolEqualityComparer.Default.Equals(paramType, method.EventType)
                   && !IsIEventGenericWrapper(paramType)
                   && !IsRawIEvent(paramType)
                   && !IsQuerySession(paramType)
                   && !IsCancellationToken(paramType)
                   && !IsEventDataType(paramType, method);
        }

        return false;
    }

    private static bool IsEventDataType(ITypeSymbol paramType, ConventionalMethodInfo method)
    {
        return SymbolEqualityComparer.Default.Equals(paramType, method.EventType);
    }

    private static bool IsIEventGenericWrapper(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            var constructedFrom = named.ConstructedFrom.ToDisplayString();
            return constructedFrom == "JasperFx.Events.IEvent<T>";
        }

        return false;
    }

    private static bool IsRawIEvent(ITypeSymbol type)
    {
        return type.ToDisplayString() == "JasperFx.Events.IEvent";
    }

    private static bool IsCancellationToken(ITypeSymbol type)
    {
        return type.ToDisplayString() == "System.Threading.CancellationToken";
    }
}
