using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Model;
using Microsoft.Extensions.DependencyInjection;
using Shouldly;

namespace CodegenTests;

public class CodegenLanguageTests
{
    [Fact]
    public void default_language_is_csharp()
    {
        new DynamicCodeBuilder(new ServiceCollection().BuildServiceProvider(), [])
            .Language.ShouldBe(CodegenLanguage.csharp);
    }

    [Fact]
    public void preview_emits_csharp_by_default()
    {
        var code = Build(CodegenLanguage.csharp).GenerateAllCode();

        code.ShouldContain("namespace");
        code.ShouldContain("class GreeterType"); // C# class syntax (F# would be "type GreeterType")
    }

    [Fact]
    public void preview_emits_fsharp_when_language_is_fsharp()
    {
        var code = Build(CodegenLanguage.fsharp).GenerateAllCode();

        code.ShouldContain("// <auto-generated/>");
        code.ShouldContain("namespace");
        code.ShouldContain("type GreeterType");
        code.ShouldNotContain("public class");
    }

    [Fact]
    public void write_uses_cs_extension_by_default()
    {
        var written = WriteToTempAndCollect(CodegenLanguage.csharp);

        written.ShouldContain(f => f.EndsWith(".cs"));
        written.ShouldNotContain(f => f.EndsWith(".fs"));
    }

    [Fact]
    public void write_uses_fs_extension_and_fsharp_content_when_language_is_fsharp()
    {
        var written = WriteToTempAndCollect(CodegenLanguage.fsharp);

        written.ShouldContain(f => f.EndsWith(".fs"));
        written.ShouldNotContain(f => f.EndsWith(".cs"));

        var fsFile = written.Single(f => f.EndsWith(".fs"));
        File.ReadAllText(fsFile).ShouldContain("namespace");
    }

    private static DynamicCodeBuilder Build(CodegenLanguage language, GenerationRules? rules = null)
    {
        var collection = new SampleCollection(rules ?? new GenerationRules("Generated"), new SampleFile("Greeter"));
        return new DynamicCodeBuilder(new ServiceCollection().BuildServiceProvider(), [collection])
        {
            Language = language
        };
    }

    private static List<string> WriteToTempAndCollect(CodegenLanguage language)
    {
        var dir = Path.Combine(Path.GetTempPath(), "jasperfx-codegen-language-" + Guid.NewGuid().ToString("n"));
        Directory.CreateDirectory(dir);
        var rules = new GenerationRules("Generated") { GeneratedCodeOutputPath = dir };

        var written = new List<string>();
        Build(language, rules).WriteGeneratedCode(written.Add);
        return written;
    }

    private sealed class SampleFile(string fileName) : ICodeFile
    {
        public string FileName { get; } = fileName;

        public void AssembleTypes(GeneratedAssembly assembly) => assembly.AddType(FileName + "Type", typeof(object));

        public Task<bool> AttachTypes(GenerationRules rules, System.Reflection.Assembly assembly,
            IServiceProvider? services, string containingNamespace) => Task.FromResult(false);

        public bool AttachTypesSynchronously(GenerationRules rules, System.Reflection.Assembly assembly,
            IServiceProvider? services, string containingNamespace) => false;

        public void AssertServiceLocationsAreAllowed(ServiceLocationReport[] reports, IServiceProvider? services) { }

        public bool TryReplaceServiceProvider(out Variable serviceProvider)
        {
            serviceProvider = default!;
            return false;
        }
    }

    private sealed class SampleCollection(GenerationRules rules, params ICodeFile[] files) : ICodeFileCollection
    {
        public string ChildNamespace => "Sample";
        public GenerationRules Rules { get; } = rules;
        public IReadOnlyList<ICodeFile> BuildFiles() => files;
    }
}
