// <auto-generated/>

namespace FSharpCodegenTarget.Generated

open FSharpCodegenTarget
open System
open System.Threading.Tasks

type GeneratedGreeter(greetingService: FSharpCodegenTarget.GreetingService) =
    let _greetingService = greetingService

    interface FSharpCodegenTarget.IGreeter with
        member this.Greet(name: string) : string =
            // Generated by JasperFx F# code generation (jasperfx#383)
            let salutation = FSharpCodegenTarget.Salutation(name)
            let result_of_CreateGreeting = _greetingService.CreateGreeting(salutation)
            let result = result_of_CreateGreeting.ToUpper()
            result

type GeneratedAsyncGreeter(greetingService: FSharpCodegenTarget.GreetingService) =
    let _greetingService = greetingService

    interface FSharpCodegenTarget.IAsyncGreeter with
        member this.GreetAsync(name: string) : System.Threading.Tasks.Task<string> =
            task {
                // Async greeting handler (jasperfx#383)
                let salutation = FSharpCodegenTarget.Salutation(name)
                let! result_of_CreateGreetingAsync = _greetingService.CreateGreetingAsync(salutation)
                return result_of_CreateGreetingAsync
            }

type GeneratedDirectAsyncGreeter(greetingService: FSharpCodegenTarget.GreetingService) =
    let _greetingService = greetingService

    interface FSharpCodegenTarget.IDirectAsyncGreeter with
        member this.GreetDirectAsync(name: string) : System.Threading.Tasks.Task<string> =
            // Returns the service Task directly (jasperfx#383)
            let salutation = FSharpCodegenTarget.Salutation(name)
            _greetingService.CreateGreetingAsync(salutation)

type GeneratedAccumulator(accumulatorService: FSharpCodegenTarget.AccumulatorService) =
    let _accumulatorService = accumulatorService

    interface FSharpCodegenTarget.IAccumulator with
        member this.Accumulate() : FSharpCodegenTarget.MutableBox =
            let mutable mutableBox = FSharpCodegenTarget.MutableBox()
            mutableBox <- _accumulatorService.Advance(mutableBox)
            mutableBox

type GeneratedConditionalGreeter(controlFlowService: FSharpCodegenTarget.ControlFlowService) =
    let _controlFlowService = controlFlowService

    interface FSharpCodegenTarget.IConditionalGreeter with
        member this.Describe(input: string) : string =
            if isNull input then
                _controlFlowService.Fallback()
            else
                _controlFlowService.Echo(input)

type GeneratedToggle(controlFlowService: FSharpCodegenTarget.ControlFlowService) =
    let _controlFlowService = controlFlowService

    interface FSharpCodegenTarget.IToggle with
        member this.Toggle(flag: bool) : unit =
            if flag then
                _controlFlowService.Record()

type GeneratedResourceRunner(controlFlowService: FSharpCodegenTarget.ControlFlowService) =
    let _controlFlowService = controlFlowService

    interface FSharpCodegenTarget.IResource with
        member this.Run() : unit =
            _controlFlowService.Begin()
            try
                _controlFlowService.Record()
            finally
                _controlFlowService.End()

type GeneratedOrderHandler(confirmationFactory: FSharpCodegenTarget.ConfirmationFactory, orderRepository: FSharpCodegenTarget.IOrderRepository) =
    let _confirmationFactory = confirmationFactory
    let _orderRepository = orderRepository

    interface FSharpCodegenTarget.IOrderHandler with
        member this.Handle(command: FSharpCodegenTarget.PlaceOrder) : System.Threading.Tasks.Task<FSharpCodegenTarget.OrderConfirmation> =
            task {
                // Handle a PlaceOrder command (jasperfx#383)
                let order = FSharpCodegenTarget.Order(command)
                do! _orderRepository.SaveAsync(order)
                let orderConfirmation = _confirmationFactory.Create(order)
                return orderConfirmation
            }

type GeneratedSyncTaskHandler(controlFlowService: FSharpCodegenTarget.ControlFlowService) =
    let _controlFlowService = controlFlowService

    interface FSharpCodegenTarget.ISyncTaskHandler with
        member this.HandleAsync(name: string) : System.Threading.Tasks.Task =
            _controlFlowService.Record()
            System.Threading.Tasks.Task.CompletedTask

type GeneratedCalculator() =
    inherit FSharpCodegenTarget.CalculatorBase()
    override this.Compute(seed: int) : int =
        let result_of_Bump = this.Bump(seed)
        result_of_Bump

type GeneratedThingHandler(thingDescriber: FSharpCodegenTarget.ThingDescriber) =
    let _thingDescriber = thingDescriber

    interface FSharpCodegenTarget.IThingHandler with
        member this.Handle() : string =
            let thing = FSharpCodegenTarget.Thing()
            _thingDescriber.Describe((thing :> FSharpCodegenTarget.IThing))

