// <auto-generated/>

namespace FSharpCodegenTarget.Generated

open FSharpCodegenTarget

type GeneratedGreeter(greetingService: FSharpCodegenTarget.GreetingService) =
    let _greetingService = greetingService

    interface FSharpCodegenTarget.IGreeter with
        member _.Greet(name: string) : string =
            // Generated by JasperFx F# code generation (jasperfx#383)
            let salutation = FSharpCodegenTarget.Salutation(name)
            let result_of_CreateGreeting = _greetingService.CreateGreeting(salutation)
            let result = result_of_CreateGreeting.ToUpper()
            result

