<Project>
  <PropertyGroup>
    <JasperFxEventsRequireSourceGenerator>true</JasperFxEventsRequireSourceGenerator>
  </PropertyGroup>
  <ItemGroup>
    <Analyzer Include="/Users/jeremymiller/code/jasperfx-794/.nuke/temp/targets-smoke/a/JasperFx.Events.SourceGenerator.dll" />
  </ItemGroup>
  <Import Project="/Users/jeremymiller/code/jasperfx-794/src/JasperFx.Events/build/JasperFx.Events.targets" />
</Project>
