// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JasperFx.SourceGeneration;

/// <summary>
/// Source generator that discovers JasperFx command types at compile time,
/// eliminating runtime assembly scanning in CommandFactory.RegisterCommandsFromExtensionAssemblies().
/// Finds all concrete classes that close JasperFxCommand&lt;T&gt; or JasperFxAsyncCommand&lt;T&gt;
/// and emits a static manifest of discovered command types.
/// </summary>
[Generator]
public sealed class CommandDiscoveryGenerator : IIncrementalGenerator
{
    private const string JasperFxCommandName = "JasperFx.CommandLine.JasperFxCommand`1";
    private const string JasperFxAsyncCommandName = "JasperFx.CommandLine.JasperFxAsyncCommand`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations that could be command types
        var commandCandidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax cds
                && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword)
                && !cds.Modifiers.Any(SyntaxKind.StaticKeyword)
                && cds.BaseList != null,
            transform: static (ctx, ct) => AnalyzeCandidate(ctx, ct))
            .Where(static info => info != null);

        // Collect all discovered commands
        var collected = commandCandidates.Collect();

        context.RegisterSourceOutput(collected, static (spc, commands) => Execute(spc, commands!));
    }

    private static CommandInfo? AnalyzeCandidate(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct);
        if (symbol == null) return null;

        // Must be a concrete (non-abstract) class
        if (symbol.IsAbstract) return null;

        // Check if it closes JasperFxCommand<T> or JasperFxAsyncCommand<T>
        if (!ClosesCommandBaseType(symbol)) return null;

        var fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeName = symbol.Name;

        // Derive command name using the same regex logic as CommandFactory.CommandNameFor:
        // Strip trailing "Command" suffix, then check for [Description] attribute Name override
        var commandName = typeName;
        if (commandName.EndsWith("Command"))
        {
            commandName = commandName.Substring(0, commandName.Length - "Command".Length);
        }

        // Check for [Description] attribute with a Name property
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "DescriptionAttribute"
                && attr.AttributeClass.ContainingNamespace?.ToDisplayString() == "JasperFx.CommandLine")
            {
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key == "Name" && named.Value.Value is string nameOverride)
                    {
                        commandName = nameOverride;
                    }
                }
            }
        }

        return new CommandInfo
        {
            FullyQualifiedTypeName = fullName,
            CommandName = commandName.ToLower(),
        };
    }

    private static bool ClosesCommandBaseType(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            var originalDef = current.OriginalDefinition?.ToDisplayString();
            if (originalDef == JasperFxCommandName || originalDef == JasperFxAsyncCommandName)
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<CommandInfo?> commands)
    {
        var validCommands = commands
            .Where(c => c != null)
            .Select(c => c!)
            .GroupBy(c => c.FullyQualifiedTypeName)
            .Select(g => g.First())
            .OrderBy(c => c.FullyQualifiedTypeName)
            .ToList();

        if (validCommands.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated manifest of JasperFx command types discovered at compile time.");
        sb.AppendLine("/// Used by CommandFactory to bypass runtime assembly scanning.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class DiscoveredCommands");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<Type> CommandTypes { get; } = new Type[]");
        sb.AppendLine("    {");

        foreach (var cmd in validCommands)
        {
            sb.AppendLine($"        typeof({cmd.FullyQualifiedTypeName}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("DiscoveredCommands.g.cs", sb.ToString());
    }
}

internal sealed class CommandInfo
{
    public string FullyQualifiedTypeName { get; set; } = "";
    public string CommandName { get; set; } = "";
}
