// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JasperFx.SourceGeneration;

/// <summary>
/// Source generator that creates optimized input model parsers for JasperFx commands.
/// For each unique input model type T used by JasperFxCommand&lt;T&gt; or JasperFxAsyncCommand&lt;T&gt;,
/// generates an IGeneratedInputParser implementation that builds ITokenHandler lists
/// without runtime reflection.
/// </summary>
[Generator]
public sealed class InputParserGenerator : IIncrementalGenerator
{
    private const string JasperFxCommandName = "JasperFx.CommandLine.JasperFxCommand`1";
    private const string JasperFxAsyncCommandName = "JasperFx.CommandLine.JasperFxAsyncCommand`1";
    private const string IgnoreAttributeName = "JasperFx.CommandLine.IgnoreOnCommandLineAttribute";
    private const string FlagAliasAttributeName = "JasperFx.CommandLine.FlagAliasAttribute";
    private const string DescriptionAttributeName = "JasperFx.CommandLine.DescriptionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandCandidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax cds
                && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword)
                && !cds.Modifiers.Any(SyntaxKind.StaticKeyword)
                && cds.BaseList != null,
            transform: static (ctx, ct) => ExtractInputType(ctx, ct))
            .Where(static info => info != null);

        var collected = commandCandidates.Collect();
        context.RegisterSourceOutput(collected, static (spc, inputs) => Execute(spc, inputs!));
    }

    private static InputModelInfo? ExtractInputType(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct);
        if (symbol == null || symbol.IsAbstract) return null;

        var inputType = FindInputType(symbol);
        if (inputType == null) return null;

        var members = CollectMembers(inputType);
        if (members.Count == 0) return null;

        return new InputModelInfo
        {
            InputTypeFullName = inputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            InputTypeName = GetSafeTypeName(inputType),
            Members = members
        };
    }

    private static INamedTypeSymbol? FindInputType(INamedTypeSymbol commandSymbol)
    {
        var current = commandSymbol.BaseType;
        while (current != null)
        {
            var originalDef = current.OriginalDefinition?.ToDisplayString();
            if (originalDef == JasperFxCommandName || originalDef == JasperFxAsyncCommandName)
            {
                if (current.TypeArguments.Length > 0 && current.TypeArguments[0] is INamedTypeSymbol inputType)
                {
                    return inputType;
                }
            }
            current = current.BaseType;
        }
        return null;
    }

    private static string GetSafeTypeName(INamedTypeSymbol type)
    {
        // Create a safe class name from fully qualified type
        return type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
            .Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");
    }

    private static List<MemberParseInfo> CollectMembers(INamedTypeSymbol inputType)
    {
        var members = new List<MemberParseInfo>();
        var seenNames = new HashSet<string>();

        // Walk the type hierarchy (including base classes like NetCoreInput)
        var current = inputType;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol prop)
                {
                    if (!prop.IsStatic && prop.DeclaredAccessibility == Accessibility.Public
                        && prop.SetMethod != null && seenNames.Add(prop.Name))
                    {
                        var info = AnalyzeMember(prop.Name, prop.Type, prop.GetAttributes(), false);
                        if (info != null) members.Add(info);
                    }
                }
                else if (member is IFieldSymbol field)
                {
                    if (!field.IsStatic && !field.IsConst && !field.IsReadOnly
                        && field.DeclaredAccessibility == Accessibility.Public
                        && seenNames.Add(field.Name))
                    {
                        var info = AnalyzeMember(field.Name, field.Type, field.GetAttributes(), true);
                        if (info != null) members.Add(info);
                    }
                }
            }
            current = current.BaseType;
        }

        return members;
    }

    private static MemberParseInfo? AnalyzeMember(string name, ITypeSymbol type,
        ImmutableArray<AttributeData> attributes, bool isField)
    {
        // Skip [IgnoreOnCommandLine]
        if (attributes.Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            return null;

        var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var description = name;
        string? flagAliasLong = null;
        char? flagAliasShort = null;
        bool flagAliasLongOnly = false;

        // Check for [Description] attribute
        foreach (var attr in attributes)
        {
            if (attr.AttributeClass?.ToDisplayString() == DescriptionAttributeName)
            {
                if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string desc)
                    description = desc;
            }
            else if (attr.AttributeClass?.ToDisplayString() == FlagAliasAttributeName)
            {
                foreach (var arg in attr.ConstructorArguments)
                {
                    if (arg.Value is string longAlias) flagAliasLong = longAlias;
                    else if (arg.Value is char shortAlias) flagAliasShort = shortAlias;
                    else if (arg.Value is bool longOnly) flagAliasLongOnly = longOnly;
                }
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key == "LongAlias" && named.Value.Value is string la) flagAliasLong = la;
                    else if (named.Key == "OneLetterAlias" && named.Value.Value is char sa) flagAliasShort = sa;
                    else if (named.Key == "LongAliasOnly" && named.Value.Value is bool lo) flagAliasLongOnly = lo;
                }
            }
        }

        bool hasFlagAlias = attributes.Any(a => a.AttributeClass?.ToDisplayString() == FlagAliasAttributeName);
        bool isFlag = name.EndsWith("Flag") || hasFlagAlias;
        bool isBool = type.SpecialType == SpecialType.System_Boolean;
        bool isDict = IsDictionaryOfStringString(type);
        bool isEnumerable = IsEnumerableButNotString(type);
        bool isEnum = type.TypeKind == TypeKind.Enum;
        bool isNullableEnum = IsNullableEnum(type);

        var handlerKind = DetermineHandlerKind(isFlag, isBool, isDict, isEnumerable);

        // Compute flag aliases
        var flagName = RemoveFlagSuffix(name);
        var longForm = SplitPascalCaseAndAddHyphens(flagAliasLong ?? flagName).ToLower();
        var shortForm = (flagAliasShort ?? longForm[0]).ToString().ToLower();

        string? elementTypeFullName = null;
        if (isEnumerable)
        {
            var elementType = GetEnumerableElementType(type);
            if (elementType != null)
                elementTypeFullName = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return new MemberParseInfo
        {
            Name = name,
            TypeFullName = typeFullName,
            Description = description,
            IsField = isField,
            HandlerKind = handlerKind,
            LongForm = "--" + longForm,
            ShortForm = "-" + shortForm,
            LongFormOnly = flagAliasLongOnly,
            IsEnum = isEnum || isNullableEnum,
            IsNullable = type.NullableAnnotation == NullableAnnotation.Annotated || IsNullableValueType(type),
            ElementTypeFullName = elementTypeFullName,
            IsNumeric = IsNumericType(type),
        };
    }

    private static HandlerKind DetermineHandlerKind(bool isFlag, bool isBool, bool isDict, bool isEnumerable)
    {
        if (!isFlag)
        {
            if (isEnumerable) return HandlerKind.EnumerableArgument;
            return HandlerKind.Argument;
        }

        if (isDict) return HandlerKind.DictionaryFlag;
        if (isEnumerable) return HandlerKind.EnumerableFlag;
        if (isBool) return HandlerKind.BooleanFlag;
        return HandlerKind.Flag;
    }

    private static bool IsDictionaryOfStringString(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
        {
            // Check IDictionary<string, string>
            if (named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>"
                && named.TypeArguments.Length == 2
                && named.TypeArguments[0].SpecialType == SpecialType.System_String
                && named.TypeArguments[1].SpecialType == SpecialType.System_String)
                return true;

            // Check Dictionary<string, string>
            if (named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.Dictionary<TKey, TValue>"
                && named.TypeArguments.Length == 2
                && named.TypeArguments[0].SpecialType == SpecialType.System_String
                && named.TypeArguments[1].SpecialType == SpecialType.System_String)
                return true;

            // Check interfaces
            foreach (var iface in named.AllInterfaces)
            {
                if (iface.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>"
                    && iface.TypeArguments.Length == 2
                    && iface.TypeArguments[0].SpecialType == SpecialType.System_String
                    && iface.TypeArguments[1].SpecialType == SpecialType.System_String)
                    return true;
            }
        }
        return false;
    }

    private static bool IsEnumerableButNotString(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String) return false;

        if (type is INamedTypeSymbol named)
        {
            if (named.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                return true;

            foreach (var iface in named.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                    return true;
            }
        }

        if (type is IArrayTypeSymbol) return true;

        return false;
    }

    private static ITypeSymbol? GetEnumerableElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array) return array.ElementType;

        if (type is INamedTypeSymbol named)
        {
            if (named.TypeArguments.Length > 0) return named.TypeArguments[0];

            foreach (var iface in named.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length > 0)
                    return iface.TypeArguments[0];
            }
        }

        return null;
    }

    private static bool IsNullableValueType(ITypeSymbol type)
    {
        return type is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
    }

    private static bool IsNullableEnum(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && named.TypeArguments.Length > 0)
        {
            return named.TypeArguments[0].TypeKind == TypeKind.Enum;
        }
        return false;
    }

    private static bool IsNumericType(ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Byte => true,
            SpecialType.System_SByte => true,
            SpecialType.System_Int16 => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_UInt16 => true,
            SpecialType.System_UInt32 => true,
            SpecialType.System_UInt64 => true,
            SpecialType.System_Single => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            _ => false
        };
    }

    private static string RemoveFlagSuffix(string name)
    {
        const string suffix = "Flag";
        if (name.Length > suffix.Length && name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            return name.Substring(0, name.Length - suffix.Length);
        return name;
    }

    private static string SplitPascalCaseAndAddHyphens(string name)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]) && (char.IsLower(name[i - 1]) ||
                (i + 1 < name.Length && char.IsLower(name[i + 1]))))
            {
                sb.Append('-');
            }
            sb.Append(name[i]);
        }
        return sb.ToString();
    }

    private static string GetConverterExpression(MemberParseInfo member)
    {
        var type = member.TypeFullName;

        // Handle Nullable<T> by stripping the nullable wrapper
        if (member.IsNullable && type.EndsWith("?"))
        {
            var innerType = type.TrimEnd('?');
            if (member.IsEnum)
            {
                return $"s => (s == \"NULL\" ? ({type})null : ({type})global::System.Enum.Parse(typeof({innerType}), s))";
            }
        }

        if (member.IsEnum)
        {
            return $"s => ({type})global::System.Enum.Parse(typeof({type}), s)";
        }

        // Known primitive types
        return type switch
        {
            "string" or "global::System.String" => "s => s == \"EMPTY\" ? string.Empty : s",
            "string?" => "s => s == \"EMPTY\" ? string.Empty : s",
            "int" or "global::System.Int32" => "s => int.Parse(s)",
            "long" or "global::System.Int64" => "s => long.Parse(s)",
            "short" or "global::System.Int16" => "s => short.Parse(s)",
            "bool" or "global::System.Boolean" => "s => bool.Parse(s)",
            "double" or "global::System.Double" => "s => double.Parse(s)",
            "float" or "global::System.Single" => "s => float.Parse(s)",
            "decimal" or "global::System.Decimal" => "s => decimal.Parse(s)",
            "byte" or "global::System.Byte" => "s => byte.Parse(s)",
            "char" or "global::System.Char" => "s => char.Parse(s)",
            "global::System.Guid" => "s => global::System.Guid.Parse(s)",
            "global::System.DateTime" => "s => global::JasperFx.CommandLine.Internal.Conversion.DateTimeConverter.GetDateTime(s)",
            "global::System.TimeSpan" => "s => global::JasperFx.CommandLine.Internal.Conversion.TimeSpanConverter.GetTimeSpan(s)",
            _ => $"new global::JasperFx.CommandLine.Internal.Conversion.Conversions().FindConverter(typeof({type}))!",
        };
    }

    private static string GetElementConverterExpression(string elementType)
    {
        return elementType switch
        {
            "string" or "global::System.String" => "s => s == \"EMPTY\" ? string.Empty : s",
            "int" or "global::System.Int32" => "s => int.Parse(s)",
            "long" or "global::System.Int64" => "s => long.Parse(s)",
            "global::System.Guid" => "s => global::System.Guid.Parse(s)",
            _ when elementType.Contains("Enum") => $"s => ({elementType})global::System.Enum.Parse(typeof({elementType}), s)",
            _ => $"s => ({elementType})new global::JasperFx.CommandLine.Internal.Conversion.Conversions().FindConverter(typeof({elementType}))!(s)",
        };
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<InputModelInfo?> inputs)
    {
        var validInputs = inputs
            .Where(i => i != null)
            .Select(i => i!)
            .GroupBy(i => i.InputTypeFullName)
            .Select(g => g.First())
            .OrderBy(i => i.InputTypeFullName)
            .ToList();

        if (validInputs.Count == 0) return;

        // Generate a parser class for each unique input model type
        foreach (var input in validInputs)
        {
            GenerateParserClass(context, input);
        }

        // Generate the registration module initializer
        GenerateRegistration(context, validInputs);
    }

    private static void GenerateParserClass(SourceProductionContext context, InputModelInfo input)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using JasperFx.CommandLine.Parsing;");
        sb.AppendLine("using JasperFx.CommandLine.Parsing.Generated;");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {input.InputTypeName}Parser : IGeneratedInputParser");
        sb.AppendLine("{");
        sb.AppendLine($"    public Type InputType => typeof({input.InputTypeFullName});");
        sb.AppendLine();
        sb.AppendLine("    public List<ITokenHandler> BuildHandlers()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new List<ITokenHandler>");
        sb.AppendLine("        {");

        foreach (var member in input.Members)
        {
            EmitHandler(sb, input, member);
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{input.InputTypeName}Parser.g.cs", sb.ToString());
    }

    private static void EmitHandler(StringBuilder sb, InputModelInfo input, MemberParseInfo member)
    {
        var inputType = input.InputTypeFullName;
        var cast = $"(({inputType})obj)";
        var memberAccess = member.IsField ? $"{cast}.{member.Name}" : $"{cast}.{member.Name}";
        var escapedDesc = member.Description.Replace("\"", "\\\"");

        switch (member.HandlerKind)
        {
            case HandlerKind.BooleanFlag:
                sb.AppendLine($"            new GeneratedBooleanFlag(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                new FlagAliases {{ LongForm = \"{member.LongForm}\", ShortForm = \"{member.ShortForm}\", LongFormOnly = {(member.LongFormOnly ? "true" : "false")} }},");
                sb.AppendLine($"                obj => {memberAccess} = true),");
                break;

            case HandlerKind.Flag:
                var converter = GetConverterExpression(member);
                sb.AppendLine($"            new GeneratedFlag<{member.TypeFullName}>(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                new FlagAliases {{ LongForm = \"{member.LongForm}\", ShortForm = \"{member.ShortForm}\", LongFormOnly = {(member.LongFormOnly ? "true" : "false")} }},");
                sb.AppendLine($"                (obj, val) => {memberAccess} = val,");
                sb.AppendLine($"                {converter},");
                sb.AppendLine($"                isEnum: {(member.IsEnum ? "true" : "false")}),");
                break;

            case HandlerKind.Argument:
                var argConverter = GetConverterExpression(member);
                sb.AppendLine($"            new GeneratedArgument<{member.TypeFullName}>(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                (obj, val) => {memberAccess} = val,");
                sb.AppendLine($"                {argConverter},");
                sb.AppendLine($"                isEnum: {(member.IsEnum ? "true" : "false")},");
                sb.AppendLine($"                isNumeric: {(member.IsNumeric ? "true" : "false")}),");
                break;

            case HandlerKind.EnumerableArgument:
                var elemType = member.ElementTypeFullName ?? "object";
                var elemConverter = GetElementConverterExpression(elemType);
                sb.AppendLine($"            new GeneratedEnumerableArgument<{elemType}>(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                (obj, val) => {memberAccess} = val,");
                sb.AppendLine($"                {elemConverter}),");
                break;

            case HandlerKind.EnumerableFlag:
                var elemType2 = member.ElementTypeFullName ?? "object";
                var elemConverter2 = GetElementConverterExpression(elemType2);
                sb.AppendLine($"            new GeneratedEnumerableFlag<{elemType2}>(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                new FlagAliases {{ LongForm = \"{member.LongForm}\", ShortForm = \"{member.ShortForm}\", LongFormOnly = {(member.LongFormOnly ? "true" : "false")} }},");
                sb.AppendLine($"                (obj, val) => {memberAccess} = val,");
                sb.AppendLine($"                {elemConverter2}),");
                break;

            case HandlerKind.DictionaryFlag:
                sb.AppendLine($"            new GeneratedDictionaryFlag(");
                sb.AppendLine($"                \"{member.Name}\",");
                sb.AppendLine($"                \"{escapedDesc}\",");
                sb.AppendLine($"                new FlagAliases {{ LongForm = \"{member.LongForm}\", ShortForm = \"{member.ShortForm}\", LongFormOnly = {(member.LongFormOnly ? "true" : "false")} }},");
                sb.AppendLine($"                obj => {memberAccess} as System.Collections.Generic.IDictionary<string, string>,");
                sb.AppendLine($"                (obj, val) => {memberAccess} = ({member.TypeFullName})val),");
                break;
        }
    }

    private static void GenerateRegistration(SourceProductionContext context, List<InputModelInfo> inputs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using JasperFx.CommandLine.Parsing;");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedParsers");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");

        foreach (var input in inputs)
        {
            sb.AppendLine($"        GeneratedParserRegistry.Register(new {input.InputTypeName}Parser());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedParsers.g.cs", sb.ToString());
    }
}

internal sealed class InputModelInfo
{
    public string InputTypeFullName { get; set; } = "";
    public string InputTypeName { get; set; } = "";
    public List<MemberParseInfo> Members { get; set; } = new();
}

internal sealed class MemberParseInfo
{
    public string Name { get; set; } = "";
    public string TypeFullName { get; set; } = "";
    public string Description { get; set; } = "";
    public bool IsField { get; set; }
    public HandlerKind HandlerKind { get; set; }
    public string LongForm { get; set; } = "";
    public string ShortForm { get; set; } = "";
    public bool LongFormOnly { get; set; }
    public bool IsEnum { get; set; }
    public bool IsNullable { get; set; }
    public string? ElementTypeFullName { get; set; }
    public bool IsNumeric { get; set; }
}

internal enum HandlerKind
{
    Argument,
    EnumerableArgument,
    Flag,
    BooleanFlag,
    EnumerableFlag,
    DictionaryFlag
}
