#nullable enable
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JasperFx.SourceGenerator;

/// <summary>
/// Discovers <c>JasperFx.Events.EventModeling.EventModelDefinition</c> subclasses at compile time and
/// emits a per-assembly <c>JasperFx.Generated.DiscoveredEventModels.DefinitionTypes</c> manifest, so
/// <c>AddDiscoveredEventModels(assembly)</c> registers an app's definitions without listing each one and
/// without an <c>Assembly.ExportedTypes</c> scan (jasperfx#993).
/// </summary>
/// <remarks>
/// <para>
/// A definition qualifies when it is concrete, public all the way out (so nested inside public types is
/// fine), not generic, and has a public constructor. The constructor may take parameters: definitions are
/// built through <c>ActivatorUtilities</c>, so constructor-injected services are allowed. The manifest
/// roots each definition's public constructors with <c>[DynamicDependency]</c> so a trimmed app keeps
/// them.
/// </para>
/// <para>
/// Emitted whenever the compilation can see <c>EventModelDefinition</c> — an empty manifest included —
/// because an empty manifest is the evidence that the generator ran: without it, the runtime cannot tell
/// "no definitions here" from "never generated", and would fall back to the reflective scan.
/// </para>
/// </remarks>
[Generator]
public sealed class EventModelDiscoveryGenerator : IIncrementalGenerator
{
    private const string DefinitionMetadataName = "JasperFx.Events.EventModeling.EventModelDefinition";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var definitions = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds
                                               && cds.BaseList != null
                                               && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword)
                                               && !cds.Modifiers.Any(SyntaxKind.StaticKeyword),
                transform: static (ctx, ct) => AnalyzeClass(ctx, ct))
            .Where(static name => name != null)
            .Collect();

        var available = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName(DefinitionMetadataName) != null);

        context.RegisterSourceOutput(definitions.Combine(available),
            static (spc, pair) => Execute(spc, pair.Left, pair.Right));
    }

    private static string? AnalyzeClass(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node, ct) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.IsStatic) return null;
        if (!DerivesFromDefinition(symbol)) return null;
        if (!IsPublicAndClosed(symbol)) return null;

        var hasPublicConstructor = symbol.InstanceConstructors.Any(c => c.DeclaredAccessibility == Accessibility.Public);
        if (!hasPublicConstructor) return null;

        return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static bool DerivesFromDefinition(INamedTypeSymbol symbol)
    {
        for (var current = symbol.BaseType; current != null; current = current.BaseType)
        {
            if (current.ToDisplayString() == DefinitionMetadataName) return true;
        }

        return false;
    }

    /// <summary>
    /// Public at every level of nesting and generic at none — the only shape a registration from
    /// another assembly can name, and one <c>typeof</c> can close.
    /// </summary>
    private static bool IsPublicAndClosed(INamedTypeSymbol symbol)
    {
        for (var current = symbol; current != null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public) return false;
            if (current.IsGenericType) return false;
        }

        return true;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<string?> definitions, bool available)
    {
        if (!available) return;

        var types = definitions
            .Where(x => x != null)
            .Select(x => x!)
            .Distinct()
            .OrderBy(x => x, System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated manifest of the EventModelDefinition subclasses in this assembly. Read by");
        sb.AppendLine("/// AddDiscoveredEventModels(assembly) in place of a reflective type scan. See jasperfx#993.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class DiscoveredEventModels");
        sb.AppendLine("{");

        // The definitions are built through ActivatorUtilities, so their public constructors must
        // survive trimming. DynamicDependency is not allowed on a property, hence the backing field.
        foreach (var type in types)
        {
            sb.AppendLine($"    [DynamicDependency(DynamicallyAccessedMemberTypes.PublicConstructors, typeof({type}))]");
        }

        sb.AppendLine("    private static readonly Type[] _definitionTypes =");
        sb.AppendLine("    {");
        foreach (var type in types)
        {
            sb.AppendLine($"        typeof({type}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyList<Type> DefinitionTypes => _definitionTypes;");
        sb.AppendLine("}");

        context.AddSource("DiscoveredEventModels.g.cs", sb.ToString());
    }
}
