// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JasperFx.SourceGenerator;

/// <summary>
/// Discovers JasperFx "extension" / "option" types at compile time, eliminating runtime
/// assembly scanning (e.g. Wolverine's ExtensionLoader + AssemblyFinder.FindAssemblies, and the
/// IServiceRegistrations discovery used by JasperFx command extensions). Emits a per-assembly
/// <c>JasperFx.Generated.DiscoveredExtensions.ExtensionTypes</c> manifest.
///
/// Only emits for assemblies that are eligible: those carrying a [JasperFxAssembly]-derived
/// assembly attribute, OR executable (entry) assemblies. Discovers via two sources, deduped:
///   1. the extension type(s) declared by the assembly's [JasperFxAssembly] / [WolverineModule&lt;T&gt;]
///      attribute (generic type arguments and typeof(...) constructor arguments), and
///   2. concrete classes implementing the <c>JasperFx.IJasperFxExtension</c> marker interface.
///
/// Consuming frameworks read the manifest from loaded assemblies and filter by the framework's
/// own extension interface (IServiceRegistrations, IWolverineExtension, ...).
/// </summary>
[Generator]
public sealed class ExtensionDiscoveryGenerator : IIncrementalGenerator
{
    private const string MarkerInterface = "JasperFx.IJasperFxExtension";
    private const string AssemblyAttribute = "JasperFx.JasperFxAssemblyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // (1) Concrete classes in this compilation implementing the marker interface.
        var markerImplementations = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds
                    && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword)
                    && !cds.Modifiers.Any(SyntaxKind.StaticKeyword)
                    && cds.BaseList != null,
                transform: static (ctx, ct) => AnalyzeClass(ctx, ct))
            .Where(static name => name != null)
            .Collect();

        // (2) Eligibility gate + assembly-attribute-declared extension types.
        var compilationInfo = context.CompilationProvider.Select(static (c, ct) => AnalyzeCompilation(c, ct));

        var combined = markerImplementations.Combine(compilationInfo);
        context.RegisterSourceOutput(combined, static (spc, pair) => Execute(spc, pair.Left, pair.Right));
    }

    // Returns the fully-qualified type name if the class implements JasperFx.IJasperFxExtension.
    private static string? AnalyzeClass(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.IsStatic)
        {
            return null;
        }

        var implementsMarker = symbol.AllInterfaces.Any(i =>
            i.ToDisplayString() == MarkerInterface);

        return implementsMarker
            ? symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : null;
    }

    private static CompilationInfo AnalyzeCompilation(Compilation compilation, CancellationToken ct)
    {
        var declared = new List<string>();
        var hasJasperFxAssemblyAttribute = false;

        foreach (var attr in compilation.Assembly.GetAttributes())
        {
            var attrClass = attr.AttributeClass;
            if (attrClass == null || !DerivesFromAssemblyAttribute(attrClass))
            {
                continue;
            }

            hasJasperFxAssemblyAttribute = true;

            // [WolverineModule<T>] — the declared type is the attribute's generic argument.
            foreach (var typeArg in attrClass.TypeArguments.OfType<INamedTypeSymbol>())
            {
                declared.Add(typeArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            // [JasperFxAssembly(typeof(T))] / [WolverineModule(typeof(T))] — typeof() ctor args.
            foreach (var arg in attr.ConstructorArguments)
            {
                if (arg.Kind == TypedConstantKind.Type && arg.Value is INamedTypeSymbol typeArg)
                {
                    declared.Add(typeArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }
        }

        var isExecutable = compilation.Options.OutputKind is OutputKind.ConsoleApplication
            or OutputKind.WindowsApplication;

        return new CompilationInfo(
            isEligible: hasJasperFxAssemblyAttribute || isExecutable,
            declaredTypes: declared.ToImmutableArray());
    }

    private static bool DerivesFromAssemblyAttribute(INamedTypeSymbol attributeClass)
    {
        for (var current = attributeClass; current != null; current = current.BaseType)
        {
            // OriginalDefinition collapses the generic WolverineModuleAttribute<T> to its open form.
            if (current.OriginalDefinition.ToDisplayString() == AssemblyAttribute
                || current.ToDisplayString() == AssemblyAttribute)
            {
                return true;
            }
        }

        return false;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<string?> markerTypes,
        CompilationInfo compilation)
    {
        if (!compilation.IsEligible)
        {
            return;
        }

        var extensionTypes = markerTypes
            .Where(x => x != null)
            .Select(x => x!)
            .Concat(compilation.DeclaredTypes)
            .Distinct()
            .OrderBy(x => x, System.StringComparer.Ordinal)
            .ToList();

        if (extensionTypes.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated manifest of JasperFx extension/option types discovered at compile time.");
        sb.AppendLine("/// Consumed by framework extension loaders to bypass runtime assembly scanning.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class DiscoveredExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<Type> ExtensionTypes { get; } = new Type[]");
        sb.AppendLine("    {");

        foreach (var type in extensionTypes)
        {
            sb.AppendLine($"        typeof({type}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("DiscoveredExtensions.g.cs", sb.ToString());
    }

    private readonly struct CompilationInfo
    {
        public CompilationInfo(bool isEligible, ImmutableArray<string> declaredTypes)
        {
            IsEligible = isEligible;
            DeclaredTypes = declaredTypes;
        }

        public bool IsEligible { get; }
        public ImmutableArray<string> DeclaredTypes { get; }
    }
}
