// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JasperFx.SourceGenerator;

/// <summary>
/// Emits actual <see cref="Microsoft.Extensions.DependencyInjection.IServiceCollection"/> registrations
/// (not just a type list) for concrete classes annotated with <c>[JasperFx.JasperFxService(...)]</c>.
/// Produces a per-assembly <c>JasperFx.Generated.GeneratedServiceRegistrations.Register(IServiceCollection)</c>
/// method full of <c>services.Add(new ServiceDescriptor(...))</c> calls — ordinary, reflection-free,
/// trim/AOT-clean code. A runtime aggregator (<c>JasperFx.GeneratedExtensionManifest</c>) invokes each
/// loaded assembly's generated method.
///
/// Only emits for eligible assemblies: those carrying a [JasperFxAssembly]-derived assembly attribute,
/// OR executable (entry) assemblies — the same gate as <see cref="ExtensionDiscoveryGenerator"/>.
/// </summary>
[Generator]
public sealed class ServiceRegistrationGenerator : IIncrementalGenerator
{
    private const string ServiceAttribute = "JasperFx.JasperFxServiceAttribute";
    private const string AssemblyAttribute = "JasperFx.JasperFxAssemblyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds
                    && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword)
                    && !cds.Modifiers.Any(SyntaxKind.StaticKeyword)
                    && cds.AttributeLists.Count > 0,
                transform: static (ctx, ct) => AnalyzeClass(ctx, ct))
            .Where(static r => r != null)
            .Collect();

        var isEligible = context.CompilationProvider.Select(static (c, _) => IsEligible(c));

        var combined = registrations.Combine(isEligible);
        context.RegisterSourceOutput(combined, static (spc, pair) => Execute(spc, pair.Left, pair.Right));
    }

    private static RegistrationData? AnalyzeClass(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.IsStatic)
        {
            return null;
        }

        var implName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var lines = new List<RegistrationLine>();

        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != ServiceAttribute)
            {
                continue;
            }

            if (attr.ConstructorArguments.Length == 0
                || attr.ConstructorArguments[0].Kind != TypedConstantKind.Type
                || attr.ConstructorArguments[0].Value is not INamedTypeSymbol serviceType)
            {
                continue;
            }

            var serviceTypeName = ResolveServiceType(serviceType, symbol);
            if (serviceTypeName == null)
            {
                // Open generic that the implementation doesn't actually close — skip rather than
                // emit code that won't compile.
                continue;
            }

            var lifetime = "Singleton";
            if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value is int lifetimeValue)
            {
                lifetime = LifetimeName(lifetimeValue);
            }

            lines.Add(new RegistrationLine(serviceTypeName, implName, lifetime));
        }

        return lines.Count == 0 ? null : new RegistrationData(lines.ToImmutableArray());
    }

    /// <summary>
    /// Returns the fully-qualified service type to register against, closing an open generic
    /// (e.g. <c>IValidator&lt;&gt;</c>) using the matching interface/base type implemented by
    /// <paramref name="impl"/>. Returns null when an open generic cannot be closed.
    /// </summary>
    private static string? ResolveServiceType(INamedTypeSymbol serviceType, INamedTypeSymbol impl)
    {
        var isOpen = serviceType.IsUnboundGenericType
            || (serviceType.IsGenericType
                && serviceType.TypeArguments.All(t => t.TypeKind == TypeKind.TypeParameter));

        if (!isOpen)
        {
            return serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var openDefinition = serviceType.OriginalDefinition;

        var match = impl.AllInterfaces.FirstOrDefault(i =>
            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, openDefinition));

        if (match == null)
        {
            for (var baseType = impl.BaseType; baseType != null; baseType = baseType.BaseType)
            {
                if (SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, openDefinition))
                {
                    match = baseType;
                    break;
                }
            }
        }

        return match?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string LifetimeName(int value)
    {
        // Microsoft.Extensions.DependencyInjection.ServiceLifetime: Singleton=0, Scoped=1, Transient=2
        return value switch
        {
            1 => "Scoped",
            2 => "Transient",
            _ => "Singleton"
        };
    }

    private static bool IsEligible(Compilation compilation)
    {
        var hasAssemblyAttribute = compilation.Assembly.GetAttributes().Any(a =>
            a.AttributeClass != null && DerivesFromAssemblyAttribute(a.AttributeClass));

        var isExecutable = compilation.Options.OutputKind is OutputKind.ConsoleApplication
            or OutputKind.WindowsApplication;

        return hasAssemblyAttribute || isExecutable;
    }

    private static bool DerivesFromAssemblyAttribute(INamedTypeSymbol attributeClass)
    {
        for (var current = attributeClass; current != null; current = current.BaseType)
        {
            // OriginalDefinition collapses a generic [WolverineModule<T>] to its open form.
            if (current.OriginalDefinition.ToDisplayString() == AssemblyAttribute
                || current.ToDisplayString() == AssemblyAttribute)
            {
                return true;
            }
        }

        return false;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RegistrationData?> data,
        bool isEligible)
    {
        if (!isEligible)
        {
            return;
        }

        var seen = new HashSet<string>();
        var lines = new List<RegistrationLine>();
        foreach (var datum in data)
        {
            if (datum == null)
            {
                continue;
            }

            foreach (var line in datum.Lines)
            {
                if (seen.Add(line.ServiceType + "|" + line.ImplementationType + "|" + line.Lifetime))
                {
                    lines.Add(line);
                }
            }
        }

        if (lines.Count == 0)
        {
            return;
        }

        lines = lines
            .OrderBy(l => l.ServiceType, System.StringComparer.Ordinal)
            .ThenBy(l => l.ImplementationType, System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JasperFx.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated dependency injection registrations for [JasperFxService]-annotated types.");
        sb.AppendLine("/// Invoked by JasperFx.GeneratedExtensionManifest to apply registrations without reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class GeneratedServiceRegistrations");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var line in lines)
        {
            sb.AppendLine(
                $"        services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({line.ServiceType}), typeof({line.ImplementationType}), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.{line.Lifetime}));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedServiceRegistrations.g.cs", sb.ToString());
    }

    private sealed class RegistrationData
    {
        public RegistrationData(ImmutableArray<RegistrationLine> lines)
        {
            Lines = lines;
        }

        public ImmutableArray<RegistrationLine> Lines { get; }
    }

    private readonly struct RegistrationLine
    {
        public RegistrationLine(string serviceType, string implementationType, string lifetime)
        {
            ServiceType = serviceType;
            ImplementationType = implementationType;
            Lifetime = lifetime;
        }

        public string ServiceType { get; }
        public string ImplementationType { get; }
        public string Lifetime { get; }
    }
}
