using System.Runtime.CompilerServices;
using FSharpCodegenTarget;
using JasperFx;
using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Frames;
using JasperFx.CodeGeneration.Model;
using JasperFx.CodeGeneration.Services;
using Microsoft.Extensions.DependencyInjection;

namespace CodegenTests.FSharp;

/// <summary>
///     Builds the canonical "milestone 1" <see cref="GeneratedAssembly" /> for F# code
///     generation (jasperfx#383): a sealed type that implements a C# interface, takes a
///     dependency through its constructor, constructs a value object, calls the injected
///     service, and returns a result. This single sample exercises all five frames wired up
///     for F# emit — <see cref="CommentFrame" />, <see cref="ConstructorFrame" />,
///     <see cref="MethodCall" />, <see cref="CodeFrame" />, and <see cref="ReturnFrame" /> —
///     plus constructor injection and interface implementation.
/// </summary>
public static class FSharpCodegenSample
{
    public static GeneratedAssembly BuildSampleAssembly()
    {
        var assembly = new GeneratedAssembly(new GenerationRules("FSharpCodegenTarget.Generated"));

        var type = assembly.AddType("GeneratedGreeter", typeof(IGreeter));
        var method = type.MethodFor(nameof(IGreeter.Greet));

        // 1. A leading comment.
        method.Frames.Add(new CommentFrame("Generated by JasperFx F# code generation (jasperfx#383)"));

        // 2. Construct a value object from the method argument: let salutation = Salutation(name)
        var salutationCtor = typeof(Salutation).GetConstructors().Single();
        method.Frames.Add(new ConstructorFrame(typeof(Salutation), salutationCtor));

        // 3. Call the constructor-injected service:
        //    let result_of_CreateGreeting = _greetingService.CreateGreeting(salutation)
        var service = new InjectedField(typeof(GreetingService), "greetingService");
        var call = new MethodCall(typeof(GreetingService), nameof(GreetingService.CreateGreeting))
        {
            Target = service
        };
        method.Frames.Add(call);

        // 4. A raw code line that creates a new variable: let result = result_of_CreateGreeting.ToUpper()
        var result = new Variable(typeof(string), "result");
        var codeFrame = (CodeFrame)method.Frames.Code("let {0} = {1}.ToUpper()", result, call.ReturnVariable!);
        ((ICodeFrame)codeFrame).Creates(result);

        // 5. Return the result (rendered as a trailing F# expression).
        method.Frames.Add(new ReturnFrame(result));

        AddAsyncType(assembly);
        AddDirectAsyncType(assembly);
        AddAccumulatorType(assembly);
        AddConditionalType(assembly);
        AddToggleType(assembly);
        AddResourceType(assembly);
        AddOrderHandlerType(assembly);
        AddSyncTaskHandlerType(assembly);
        AddCalculatorType(assembly);
        AddCastType(assembly);
        AddScopedConsumerType(assembly);

        return assembly;
    }

    /// <summary>
    ///     A handler that resolves a service-located <see cref="IScopedThing" /> and awaits it.
    ///     Exercises the scoped-DI frames: <c>use serviceScope = …CreateAsyncScope(…)</c> +
    ///     <c>let scopedThing = …GetRequiredService&lt;IScopedThing&gt;(serviceScope.ServiceProvider)</c>
    ///     (jasperfx#397). Rendered with a ServiceCollectionServerVariableSource whose IScopedThing is
    ///     an opaque scoped lambda factory (forcing service location).
    /// </summary>
    private static void AddScopedConsumerType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedScopedConsumer", typeof(IScopedConsumerHandler));
        var method = type.MethodFor(nameof(IScopedConsumerHandler.Handle));

        // No Target — IScopedThing is resolved by the service-variable source (scoped lambda factory),
        // which inserts ScopedContainerCreation + GetServiceFromScopedContainerFrame. Two awaits make
        // the body a task { } (AsyncTask), exercising the `use … CreateAsyncScope()` path.
        method.Frames.Add(new MethodCall(typeof(IScopedThing), nameof(IScopedThing.DoAsync)));
        method.Frames.Add(new MethodCall(typeof(IScopedThing), nameof(IScopedThing.DoAsync)));
    }

    /// <summary>
    ///     Constructs a concrete <see cref="Thing" /> and passes it to a service expecting the
    ///     <see cref="IThing" /> interface via a <see cref="CastVariable" />. Exercises the F# cast
    ///     operator: the argument renders as <c>(thing :> IThing)</c> rather than a C-style cast
    ///     (jasperfx#395).
    /// </summary>
    private static void AddCastType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedThingHandler", typeof(IThingHandler));
        var method = type.MethodFor(nameof(IThingHandler.Handle));

        var ctor = new ConstructorFrame(typeof(Thing), typeof(Thing).GetConstructors().Single());
        method.Frames.Add(ctor);

        var service = new InjectedField(typeof(ThingDescriber), "thingDescriber");
        var call = new MethodCall(typeof(ThingDescriber), nameof(ThingDescriber.Describe))
        {
            Target = service,
            ReturnAction = ReturnAction.Return
        };
        call.Arguments[0] = new CastVariable(ctor.Variable, typeof(IThing));
        method.Frames.Add(call);
    }

    /// <summary>
    ///     A subclass that overrides a base abstract method and calls an inherited instance method via a
    ///     local (this-qualified) <see cref="MethodCall" />. Exercises the named-self F# emit: the member
    ///     renders as <c>override this.Compute</c> and the call as <c>this.Bump(seed)</c> (jasperfx#393).
    /// </summary>
    private static void AddCalculatorType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedCalculator", typeof(CalculatorBase));
        var method = type.MethodFor(nameof(CalculatorBase.Compute));
        var seed = method.Arguments[0];

        var bump = new MethodCall(typeof(CalculatorBase), nameof(CalculatorBase.Bump)) { IsLocal = true };
        bump.Arguments[0] = seed;
        method.Frames.Add(bump);

        method.Frames.Add(new ReturnFrame(bump.ReturnVariable!));
    }

    /// <summary>
    ///     A synchronous body behind a non-generic <c>Task</c> signature: the side effect runs, then
    ///     the method yields <c>Task.CompletedTask</c> (AsyncMode.None + Task return).
    /// </summary>
    private static void AddSyncTaskHandlerType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedSyncTaskHandler", typeof(ISyncTaskHandler));
        var method = type.MethodFor(nameof(ISyncTaskHandler.HandleAsync));

        var service = new InjectedField(typeof(ControlFlowService), "controlFlowService");
        method.Frames.Add(new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Record))
        {
            Target = service
        });
    }

    /// <summary>
    ///     A Wolverine-shaped async handler: construct a domain object from the command, <c>do!</c>
    ///     an async repository save, build a confirmation with a sync factory call, and return it.
    ///     Exercises mixed sync/async frames inside a single <c>task { }</c> body.
    /// </summary>
    private static void AddOrderHandlerType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedOrderHandler", typeof(IOrderHandler));
        var method = type.MethodFor(nameof(IOrderHandler.Handle));
        var command = method.Arguments[0];

        method.Frames.Add(new CommentFrame("Handle a PlaceOrder command (jasperfx#383)"));

        var orderCtor = typeof(Order).GetConstructors().Single();
        var ctorFrame = new ConstructorFrame(typeof(Order), orderCtor);
        ctorFrame.Parameters[0] = command;
        method.Frames.Add(ctorFrame);

        var repository = new InjectedField(typeof(IOrderRepository), "orderRepository");
        var save = new MethodCall(typeof(IOrderRepository), nameof(IOrderRepository.SaveAsync))
        {
            Target = repository
        };
        save.Arguments[0] = ctorFrame.Variable;
        method.Frames.Add(save);

        var factory = new InjectedField(typeof(ConfirmationFactory), "confirmationFactory");
        var create = new MethodCall(typeof(ConfirmationFactory), nameof(ConfirmationFactory.Create))
        {
            Target = factory
        };
        create.Arguments[0] = ctorFrame.Variable;
        method.Frames.Add(create);

        method.Frames.Add(new ReturnFrame(create.ReturnVariable!));
    }

    /// <summary>
    ///     A null-guard that returns one of two values — F# <c>if isNull x then ... else ...</c>
    ///     as the trailing (return) expression (IfElseNullGuardFrame).
    /// </summary>
    private static void AddConditionalType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedConditionalGreeter", typeof(IConditionalGreeter));
        var method = type.MethodFor(nameof(IConditionalGreeter.Describe));
        var input = method.Arguments[0];

        var service = new InjectedField(typeof(ControlFlowService), "controlFlowService");

        var fallback = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Fallback))
        {
            Target = service, ReturnAction = ReturnAction.Return
        };
        var echo = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Echo))
        {
            Target = service, ReturnAction = ReturnAction.Return
        };
        echo.Arguments[0] = input;

        method.Frames.Add(new IfElseNullGuardFrame(input, new Frame[] { fallback }, new Frame[] { echo }));
    }

    /// <summary>
    ///     A conditional side effect — F# <c>if flag then ...</c> (IfBlock, a CompositeFrame).
    /// </summary>
    private static void AddToggleType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedToggle", typeof(IToggle));
        var method = type.MethodFor(nameof(IToggle.Toggle));
        var flag = method.Arguments[0];

        var service = new InjectedField(typeof(ControlFlowService), "controlFlowService");
        var record = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Record))
        {
            Target = service
        };

        method.Frames.Add(new IfBlock(flag, record));
    }

    /// <summary>
    ///     A try/finally — F# <c>try ... finally ...</c> (TryFinallyWrapperFrame).
    /// </summary>
    private static void AddResourceType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedResourceRunner", typeof(IResource));
        var method = type.MethodFor(nameof(IResource.Run));

        var service = new InjectedField(typeof(ControlFlowService), "controlFlowService");
        var begin = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Begin))
        {
            Target = service
        };
        var work = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.Record))
        {
            Target = service
        };
        var end = new MethodCall(typeof(ControlFlowService), nameof(ControlFlowService.End))
        {
            Target = service
        };

        method.Frames.Add(new TryFinallyWrapperFrame(begin, new Frame[] { end }));
        method.Frames.Add(work);
    }

    /// <summary>
    ///     A second type whose method is asynchronous, so the body is wrapped in a
    ///     <c>task { }</c> computation expression with <c>let!</c> (await) and <c>return</c>.
    /// </summary>
    private static void AddAsyncType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedAsyncGreeter", typeof(IAsyncGreeter));
        var method = type.MethodFor(nameof(IAsyncGreeter.GreetAsync));

        method.Frames.Add(new CommentFrame("Async greeting handler (jasperfx#383)"));

        var salutationCtor = typeof(Salutation).GetConstructors().Single();
        method.Frames.Add(new ConstructorFrame(typeof(Salutation), salutationCtor));

        var service = new InjectedField(typeof(GreetingService), "greetingService");
        var call = new MethodCall(typeof(GreetingService), nameof(GreetingService.CreateGreetingAsync))
        {
            Target = service
        };
        method.Frames.Add(call);

        method.Frames.Add(new ReturnFrame(call.ReturnVariable!));
    }

    /// <summary>
    ///     A type whose single async call IS the return value, so the body is a bare trailing
    ///     Task expression (ReturnFromLastNode) — no <c>task { }</c> state machine.
    /// </summary>
    private static void AddDirectAsyncType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedDirectAsyncGreeter", typeof(IDirectAsyncGreeter));
        var method = type.MethodFor(nameof(IDirectAsyncGreeter.GreetDirectAsync));

        method.Frames.Add(new CommentFrame("Returns the service Task directly (jasperfx#383)"));

        var salutationCtor = typeof(Salutation).GetConstructors().Single();
        method.Frames.Add(new ConstructorFrame(typeof(Salutation), salutationCtor));

        var service = new InjectedField(typeof(GreetingService), "greetingService");
        var call = new MethodCall(typeof(GreetingService), nameof(GreetingService.CreateGreetingAsync))
        {
            Target = service,
            // The call itself is the method's return value — no ReturnFrame after it.
            ReturnAction = ReturnAction.Return
        };
        method.Frames.Add(call);
    }

    /// <summary>
    ///     A type that constructs a local, reassigns it from a service call, and returns it —
    ///     exercising F# <c>let mutable</c> + the <c>&lt;-</c> reassignment operator.
    /// </summary>
    private static void AddAccumulatorType(GeneratedAssembly assembly)
    {
        var type = assembly.AddType("GeneratedAccumulator", typeof(IAccumulator));
        var method = type.MethodFor(nameof(IAccumulator.Accumulate));

        var boxCtor = typeof(MutableBox).GetConstructors().Single();
        var ctorFrame = new ConstructorFrame(typeof(MutableBox), boxCtor);
        method.Frames.Add(ctorFrame);

        var service = new InjectedField(typeof(AccumulatorService), "accumulatorService");
        var call = new MethodCall(typeof(AccumulatorService), nameof(AccumulatorService.Advance))
        {
            Target = service
        };
        call.Arguments[0] = ctorFrame.Variable;
        call.AssignResultTo(ctorFrame.Variable); // box <- service.Advance(box) (marks box mutable)
        method.Frames.Add(call);

        method.Frames.Add(new ReturnFrame(ctorFrame.Variable));
    }

    /// <summary>
    ///     Builds the sample and renders it as F# source.
    /// </summary>
    public static string GenerateCode()
    {
        // A service-variable source backed by a scoped lambda-factory registration so the
        // GeneratedScopedConsumer resolves IScopedThing via service location (the scoped-DI frames).
        // The other sample types use constructor injection and are unaffected by the source.
        var services = new ServiceCollection();
        services.AddScoped<IScopedThing>(_ => new ScopedThing());
        var container = new ServiceContainer(services, services.BuildServiceProvider());
        var source = new ServiceCollectionServerVariableSource(container);

        return BuildSampleAssembly().GenerateFSharpCode(source);
    }

    /// <summary>
    ///     The checked-in fixture's <c>Generated.fs</c>, located relative to this source file so it
    ///     resolves regardless of the test runner's working directory or bin layout.
    /// </summary>
    public static string DefaultGeneratedFilePath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcDir, "CodegenTests.FSharpFixture", "Generated.fs");
    }

    public static string FixtureProjectPath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcDir, "CodegenTests.FSharpFixture", "CodegenTests.FSharpFixture.fsproj");
    }
}
