using System.Runtime.CompilerServices;
using FSharpCodegenTarget;
using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Frames;
using JasperFx.CodeGeneration.Model;

namespace CodegenTests.FSharp;

/// <summary>
///     Builds the canonical "milestone 1" <see cref="GeneratedAssembly" /> for F# code
///     generation (jasperfx#383): a sealed type that implements a C# interface, takes a
///     dependency through its constructor, constructs a value object, calls the injected
///     service, and returns a result. This single sample exercises all five frames wired up
///     for F# emit — <see cref="CommentFrame" />, <see cref="ConstructorFrame" />,
///     <see cref="MethodCall" />, <see cref="CodeFrame" />, and <see cref="ReturnFrame" /> —
///     plus constructor injection and interface implementation.
/// </summary>
public static class FSharpCodegenSample
{
    public static GeneratedAssembly BuildSampleAssembly()
    {
        var assembly = new GeneratedAssembly(new GenerationRules("FSharpCodegenTarget.Generated"));

        var type = assembly.AddType("GeneratedGreeter", typeof(IGreeter));
        var method = type.MethodFor(nameof(IGreeter.Greet));

        // 1. A leading comment.
        method.Frames.Add(new CommentFrame("Generated by JasperFx F# code generation (jasperfx#383)"));

        // 2. Construct a value object from the method argument: let salutation = Salutation(name)
        var salutationCtor = typeof(Salutation).GetConstructors().Single();
        method.Frames.Add(new ConstructorFrame(typeof(Salutation), salutationCtor));

        // 3. Call the constructor-injected service:
        //    let result_of_CreateGreeting = _greetingService.CreateGreeting(salutation)
        var service = new InjectedField(typeof(GreetingService), "greetingService");
        var call = new MethodCall(typeof(GreetingService), nameof(GreetingService.CreateGreeting))
        {
            Target = service
        };
        method.Frames.Add(call);

        // 4. A raw code line that creates a new variable: let result = result_of_CreateGreeting.ToUpper()
        var result = new Variable(typeof(string), "result");
        var codeFrame = (CodeFrame)method.Frames.Code("let {0} = {1}.ToUpper()", result, call.ReturnVariable!);
        ((ICodeFrame)codeFrame).Creates(result);

        // 5. Return the result (rendered as a trailing F# expression).
        method.Frames.Add(new ReturnFrame(result));

        return assembly;
    }

    /// <summary>
    ///     Builds the sample and renders it as F# source.
    /// </summary>
    public static string GenerateCode()
    {
        return BuildSampleAssembly().GenerateFSharpCode();
    }

    /// <summary>
    ///     The checked-in fixture's <c>Generated.fs</c>, located relative to this source file so it
    ///     resolves regardless of the test runner's working directory or bin layout.
    /// </summary>
    public static string DefaultGeneratedFilePath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcDir, "CodegenTests.FSharpFixture", "Generated.fs");
    }

    public static string FixtureProjectPath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcDir, "CodegenTests.FSharpFixture", "CodegenTests.FSharpFixture.fsproj");
    }
}
