name: DotNet CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'
      - 'docs/**'
      - 'azure-pipelines.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'
      - 'docs/**'
      - 'azure-pipelines.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  node_version: 16.x
  pg_db: marten_testing
  pg_user: postgres
  CONFIGURATION: Release
  FRAMEWORK: net9.0
  DISABLE_TEST_PARALLELIZATION: true
  NUKE_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install .NET 9.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: compile
        run: ./build.sh compile
        shell: bash

      - name: test-core
        if: ${{ success() || failure() }}
        run: ./build.sh test-core
        shell: bash

      - name: test-codegen
        if: ${{ success() || failure() }}
        run: ./build.sh test-codegen
        shell: bash

      - name: test-command-line
        if: ${{ success() || failure() }}
        run: ./build.sh test-command-line
        shell: bash
